const test=require('node:test');const assert=require('node:assert/strict');const {makeCheckpoint,resume,sample}=require('../scripts/marketing-mission-resume-sim');
test('resumes at first uncompleted verified stage',()=>{const r=resume(sample(),'scope1');assert.equal(r.decision,'resume');assert.equal(r.resume_stage,'approval');assert.equal(r.external_execution,false)});
test('tampered checkpoint blocks',()=>{const c=sample();c.next_stage='distribution';assert.equal(resume(c,'scope1').decision,'blocked_integrity')});
test('scope change blocks',()=>assert.equal(resume(sample(),'scope2').decision,'blocked_scope'));
test('skipped completed stage blocks',()=>{const c=makeCheckpoint({...sample(),completed_stages:['objective','creative'],next_stage:'production',stage_evidence:{objective:'e1',creative:'e3'}});assert.equal(resume(c,'scope1').decision,'blocked_sequence')});
test('missing evidence for completed stage blocks',()=>{const c=makeCheckpoint({...sample(),stage_evidence:{objective:'e1',research:'e2',creative:'e3',production:'e4'}});assert.equal(resume(c,'scope1').reason,'missing_stage_evidence')});
test('wrong next stage blocks',()=>{const c=makeCheckpoint({...sample(),next_stage:'distribution'});assert.equal(resume(c,'scope1').reason,'next_stage_mismatch')});
test('checkpoint after approval resumes at distribution',()=>{const c=makeCheckpoint({...sample(),completed_stages:['objective','research','creative','production','qa','approval'],next_stage:'distribution',stage_evidence:{...sample().stage_evidence,approval:'e6'}});assert.equal(resume(c,'scope1').resume_stage,'distribution')});
test('completed run does not resume',()=>{const evidence={};['objective','research','creative','production','qa','approval','distribution','measurement','learning','replanning'].forEach((s,i)=>evidence[s]='e'+i);const c=makeCheckpoint({...sample(),completed_stages:Object.keys(evidence),next_stage:'completed',stage_evidence:evidence});assert.equal(resume(c,'scope1').decision,'completed')});
