'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {createHermesMaintainerGithubCreatePullRequestTransport,URL}=require('../src/core/hermes-maintainer-github-create-pull-request-transport');
const auth={ok:true,authorization:'Bearer synthetic'};const signal=()=>new AbortController().signal;const req=()=>({method:'POST',url:URL,body:{title:'feat(hermes): controlled PR',body:'Simulation-first PR.',head:'hermes/example-change',base:'main',draft:true},intent_digest:'sha256:'+'1'.repeat(64),attempt_reference:'attempt-pr-1',capability_reference:'cap-pr-1',admission_reference:'admission-pr-1'});
const make=(fetchImpl=async()=>({status:201,json:async()=>({number:408,html_url:'https://github.com/instutodp-cpu/agente-grupo-erick/pull/408',draft:true})}),resolveAuthorization=async()=>auth)=>createHermesMaintainerGithubCreatePullRequestTransport({fetchImpl,resolveAuthorization,createTimeoutSignal:signal});
test('uses exact POST endpoint and confirms only a draft PR identity on HTTP 201',async()=>{let seen;const r=await make(async(url,o)=>{seen={url,o};return {status:201,json:async()=>({number:408,html_url:'https://github.com/instutodp-cpu/agente-grupo-erick/pull/408',draft:true})};}).createPullRequest(req());assert.equal(r.status,'CREATED');assert.equal(r.created,true);assert.equal(r.pull_request_number,408);assert.equal(r.network_call_performed,true);assert.equal(r.write_performed,false);assert.equal(seen.url,URL);assert.deepEqual(JSON.parse(seen.o.body),req().body);});
test('rejects unsafe scope before fetch',async()=>{for(const patch of [{url:'https://api.github.com/repos/other/repo/pulls'},{body:{...req().body,base:'dev'}},{body:{...req().body,head:'main'}},{body:{...req().body,draft:false}},{extra:true}]){let calls=0;const r=await make(async()=>{calls++;return {status:201};}).createPullRequest({...req(),...patch});assert.equal(calls,0);assert.equal(r.status,'BLOCKED');}});
test('missing authorization blocks before fetch',async()=>{let calls=0;const r=await make(async()=>{calls++;return {status:201};},async()=>null).createPullRequest(req());assert.equal(calls,0);assert.equal(r.reason,'AUTHORIZATION_UNAVAILABLE');});
test('non-201 never confirms creation',async()=>{for(const status of [200,401,403,404,409,422,500]){const r=await make(async()=>({status})).createPullRequest(req());assert.equal(r.created,false);assert.equal(r.status,'FAILED');assert.equal(r.provider_status,status);}});
test('201 with non-draft or invalid identity never confirms creation',async()=>{for(const payload of [{number:408,html_url:'https://github.com/instutodp-cpu/agente-grupo-erick/pull/408',draft:false},{number:0,html_url:'https://github.com/instutodp-cpu/agente-grupo-erick/pull/408',draft:true},{number:408,html_url:'https://attacker.invalid/pull/408',draft:true}]){const r=await make(async()=>({status:201,json:async()=>payload})).createPullRequest(req());assert.equal(r.created,false);assert.equal(r.reason,'PROVIDER_RESULT_IDENTITY_INVALID');}});
test('transport never exposes credential material or production use',async()=>{const r=await make().createPullRequest(req());assert.equal(r.credential_material_present,false);assert.equal(r.production_used,false);assert.equal(JSON.stringify(r).includes('synthetic'),false);});
