'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bindHermesMaintainerSafeWorkflowControlledExecution}=require('../src/core/hermes-maintainer-safe-workflow-controlled-execution');
const {prepareHermesMaintainerSafeWorkflowAuthorityEntry}=require('../src/core/hermes-maintainer-safe-workflow-authority-entry-composition');
const workflow='sha256:'+'a'.repeat(64),globalIntent='sha256:'+'b'.repeat(64),binding='sha256:'+'c'.repeat(64),scmIntent='sha256:'+'d'.repeat(64);
function controlled(){const handoff={contract_version:'hermes_maintainer_safe_workflow_execution_handoff_v1',mission_id:'m1',workflow_digest:workflow,intent_digest:globalIntent,intent_count:7,authorization_binding_digest:binding,status:'MAINTAINER_SAFE_WORKFLOW_EXECUTION_HANDOFF_PREPARED_SIMULATION',handoff_prepared:true,execution_eligible:false,execution_authorized:false,authority_consumed:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[]};const execution={contract_version:'hermes_maintainer_controlled_executor_v1',mission_id:'m1',operation:'branch_prepare',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',status:'MAINTAINER_CONTROLLED_EXECUTION_PREPARED_SIMULATION',execution_prepared:true,execution_eligible:false,execution_authorized:false,network_authorized:false,credentials_authorized:false,write_authorized:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[]};return bindHermesMaintainerSafeWorkflowControlledExecution(handoff,execution);}
function ownership(o={}){return {contract_version:'hermes_maintainer_scm_write_durable_ownership_binding_v1',status:'SCM_WRITE_DURABLE_OWNERSHIP_BOUND',binding_valid:true,ownership_source:'DURABLE_PERSISTENCE_RECEIPT',ownership_key:'persist-1::attempt-ownership',persistence_key:'persist-1',intent_digest:scmIntent,authorization_reference:'auth-1',consumption_reference:'consume-1',attempt_reference:'attempt-1',durable_replay_protection:true,ownership_exclusive:true,execution_authorized:false,credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,blockers:[],...o};}
function evidence(o={}){return {decision:'GRANTED',capability:'github_create_branch_staging',intent_digest:scmIntent,attempt_reference:'attempt-1',capability_reference:'cap-1',approval_reference:'approval-1',authorization_reference:'auth-1',...o};}
function target(){return {operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',base_sha:'1'.repeat(40),branch_name:'hermes/canary/test'};}
test('fails closed before ownership or authority when controlled execution is invalid',()=>{const out=prepareHermesMaintainerSafeWorkflowAuthorityEntry({},{});assert.equal(out.status,'MAINTAINER_SAFE_WORKFLOW_AUTHORITY_ENTRY_BLOCKED');assert.equal(out.stage,'operation_route');assert.equal(out.authority_requirement,null);assert.equal(out.merge_authority,false);assert.equal(out.human_merge_required,true);});
test('bridges distinct workflow and SCM intent digests before durable ownership binding',()=>{const out=prepareHermesMaintainerSafeWorkflowAuthorityEntry(controlled(),{ownership:ownership(),target:target(),authority_evidence:evidence()});assert.notEqual(globalIntent,scmIntent);assert.notEqual(out.stage,'operational_authority_bridge');assert.notEqual(out.stage,'ownership_binding');});
test('fails closed when operational authority evidence is swapped to another SCM intent',()=>{const out=prepareHermesMaintainerSafeWorkflowAuthorityEntry(controlled(),{ownership:ownership(),target:target(),authority_evidence:evidence({intent_digest:'sha256:'+'e'.repeat(64)})});assert.equal(out.prepared,false);assert.equal(out.stage,'operational_authority_bridge');assert.equal(out.value.bridge_valid,false);});
test('fails closed when operational authority evidence is for another capability',()=>{const out=prepareHermesMaintainerSafeWorkflowAuthorityEntry(controlled(),{ownership:ownership(),target:target(),authority_evidence:evidence({capability:'github_update_file_hermes_branch_staging'})});assert.equal(out.prepared,false);assert.equal(out.stage,'operational_authority_bridge');});
test('module does not expose an authority grant operation',()=>{const mod=require('../src/core/hermes-maintainer-safe-workflow-authority-entry-composition');assert.equal(typeof mod.grantAuthority,'undefined');assert.equal(typeof mod.authorize,'undefined');});
