'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildHermesMaintainerScmWriteIntent}=require('../src/core/hermes-maintainer-scm-write-intent');
const {fingerprintHermesMaintainerScmWriteIntent}=require('../src/core/hermes-maintainer-scm-write-intent-fingerprint');
const {buildHermesMaintainerScmWriteApprovalRequest}=require('../src/core/hermes-maintainer-scm-write-approval-request');
const {bindHermesMaintainerScmWriteApproval}=require('../src/core/hermes-maintainer-scm-write-approval-binding');
function request(){const i=buildHermesMaintainerScmWriteIntent({provider:'GITHUB',operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',branch_name:'hermes/example-change'});const f=fingerprintHermesMaintainerScmWriteIntent(i);return buildHermesMaintainerScmWriteApprovalRequest(i,f);}
test('binds explicit approval to the exact intent digest without authorizing execution',()=>{const r=request();const b=bindHermesMaintainerScmWriteApproval(r,{decision:'APPROVED',intent_digest:r.intent_digest,approval_reference:'human-review-1'});assert.equal(b.status,'SCM_WRITE_APPROVAL_BOUND');assert.equal(b.approval_valid,true);assert.equal(b.human_approval_present,true);assert.equal(b.execution_authorized,false);assert.equal(b.network_call_performed,false);assert.equal(b.write_performed,false);});
test('fails closed when approval digest does not match the requested target',()=>{const r=request();const b=bindHermesMaintainerScmWriteApproval(r,{decision:'APPROVED',intent_digest:'sha256:'+'0'.repeat(64),approval_reference:'human-review-2'});assert.equal(b.approval_valid,false);assert.ok(b.blockers.includes('APPROVAL_DIGEST_MISMATCH'));assert.equal(b.human_approval_present,false);});
test('rejected or unreferenced decisions never become approval',()=>{const r=request();for(const a of [{decision:'REJECTED',intent_digest:r.intent_digest,approval_reference:'human-review-3'},{decision:'APPROVED',intent_digest:r.intent_digest,approval_reference:''}]){const b=bindHermesMaintainerScmWriteApproval(r,a);assert.equal(b.approval_valid,false);assert.equal(b.execution_authorized,false);assert.equal(b.write_performed,false);}});
