'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {bindHermesMaintainerSafeWorkflowControlledExecution,validateHermesMaintainerSafeWorkflowControlledExecution}=require('../src/core/hermes-maintainer-safe-workflow-controlled-execution');
const d='sha256:'+'a'.repeat(64),i='sha256:'+'b'.repeat(64),b='sha256:'+'c'.repeat(64);
function handoff(o={}){return {contract_version:'hermes_maintainer_safe_workflow_execution_handoff_v1',mission_id:'m1',workflow_digest:d,intent_digest:i,intent_count:7,authorization_binding_digest:b,status:'MAINTAINER_SAFE_WORKFLOW_EXECUTION_HANDOFF_PREPARED_SIMULATION',handoff_prepared:true,execution_eligible:false,execution_authorized:false,authority_consumed:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
function execution(o={}){return {contract_version:'hermes_maintainer_controlled_executor_v1',mission_id:'m1',operation:'repository_read',repository:'owner/repo',base_ref:'main',status:'MAINTAINER_CONTROLLED_EXECUTION_PREPARED_SIMULATION',execution_prepared:true,execution_eligible:false,execution_authorized:false,network_authorized:false,credentials_authorized:false,write_authorized:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
test('binds safe workflow to controlled execution without authority',()=>{const x=bindHermesMaintainerSafeWorkflowControlledExecution(handoff(),execution());assert.equal(x.execution_prepared,true);assert.equal(x.execution_authorized,false);assert.equal(x.merge_authority,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowControlledExecution(x),{valid:true,errors:[]});});
test('fails closed when mission differs',()=>{const x=bindHermesMaintainerSafeWorkflowControlledExecution(handoff(),execution({mission_id:'m2'}));assert.equal(x.execution_prepared,false);assert.ok(x.blockers.includes('mission_id_mismatch'));assert.equal(x.operational_authority_consumed,false);});
test('fails closed when controlled execution is not ready',()=>{const x=bindHermesMaintainerSafeWorkflowControlledExecution(handoff(),execution({status:'MAINTAINER_CONTROLLED_EXECUTION_BLOCKED',execution_prepared:false,blockers:['blocked']}));assert.equal(x.execution_prepared,false);assert.ok(x.blockers.includes('controlled_execution_not_ready'));assert.equal(x.write_authorized,false);});
