'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createHermesMaintainerGithubUpdateFileFinalizationPostgresPersistenceComposition}=require('../src/core/hermes-maintainer-github-update-file-finalization-postgres-persistence-composition');
const {createHermesMaintainerGithubUpdateFileOperationalFinalizationComposition}=require('../src/runtime/hermes-maintainer-github-update-file-operational-finalization-composition');
test('finalization postgres composition requires durable pool',()=>{assert.throws(()=>createHermesMaintainerGithubUpdateFileFinalizationPostgresPersistenceComposition({}),/postgres_pool_required/);});
test('operational finalization requires durable pool',()=>{assert.throws(()=>createHermesMaintainerGithubUpdateFileOperationalFinalizationComposition({}),/postgres_pool_required/);});
test('finalization postgres composition remains persistence-only',()=>{const pool={connect(){},query(){}};const c=createHermesMaintainerGithubUpdateFileFinalizationPostgresPersistenceComposition({pool});assert.equal(c.persistence_backend,'POSTGRES');assert.equal(c.durable_finalization_enabled,true);assert.equal(c.credential_resolution_enabled,false);assert.equal(c.github_transport_enabled,false);assert.equal(c.execution_enabled,false);});

test('operational finalization durably preserves provider result identity',async()=>{
 const admission={contract_version:'hermes_maintainer_github_update_file_durable_admission_v1',status:'GITHUB_UPDATE_FILE_DURABLE_REQUEST_ADMITTED',admission_valid:true,execution_authorized:true,provider:'GITHUB',operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',ownership_source:'DURABLE_PERSISTENCE_RECEIPT',intent_digest:'sha256:'+'1'.repeat(64),attempt_reference:'attempt-1',capability_reference:'cap-1',admission_reference:'adm-1',persistence_key:'persist-1',ownership_key:'persist-1::attempt-ownership',request:{method:'PUT',url:'https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/docs/a.md',body:{message:'x',content:'eA==',sha:'a'.repeat(40),branch:'hermes/x'}}};
 const execution={contract_version:'hermes_maintainer_github_update_file_durable_execution_boundary_v1',status:'GITHUB_UPDATE_FILE_DURABLE_EXECUTION_SUCCEEDED',execution_performed:true,network_call_performed:true,write_performed:true,production_used:false,provider_status:200,new_blob_sha:'b'.repeat(40),commit_sha:'c'.repeat(40),blockers:[]};
 const rows=new Map();const client={query:async(sql,v)=>{if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[]};if(sql.startsWith('INSERT INTO hermes.maintainer_github_update_file_execution_outcome')){rows.set(v[0],{outcome_key:v[0],outcome_digest:v[1],intent_digest:v[2],attempt_reference:v[3],admission_reference:v[4],repository:v[5],operation:v[6],branch:v[7],path:v[8],previous_blob_sha:v[9],new_blob_sha:v[10],commit_sha:v[11],provider_status:v[12]});return {rows:[{outcome_key:v[0]}]};}if(sql.startsWith('INSERT INTO hermes.maintainer_github_update_file_finalization')){rows.set(v[0],{finalization_key:v[0],finalization_digest:v[1],outcome_digest:v[2],intent_digest:v[3],attempt_reference:v[4],admission_reference:v[5],repository:v[6],operation:v[7],branch:v[8],path:v[9],previous_blob_sha:v[10],new_blob_sha:v[11],commit_sha:v[12],provider_status:v[13]});return {rows:[{finalization_key:v[0]}]};}if(sql.startsWith('SELECT '))return {rows:[rows.get(v[0])]};throw new Error('unexpected query');},release(){}};
 const pool={connect:async()=>client,query:async(_sql,v)=>({rows:[rows.get(v[0])]})};
 const result=await createHermesMaintainerGithubUpdateFileOperationalFinalizationComposition({pool}).finalize(admission,execution);
 assert.equal(result.status,'UPDATE_FILE_OPERATIONAL_FINALIZATION_CONFIRMED');assert.equal(result.durable,true);assert.equal(result.receipt.previous_blob_sha,'a'.repeat(40));assert.equal(result.receipt.new_blob_sha,'b'.repeat(40));assert.equal(result.receipt.commit_sha,'c'.repeat(40));assert.equal(result.receipt.provider_status,200);assert.equal(result.network_call_performed,false);assert.equal(result.write_performed,false);assert.equal(result.production_used,false);
});
