'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createHermesMaintainerGithubUpdateFileE2eDurableClosure}=require('../src/runtime/hermes-maintainer-github-update-file-e2e-durable-closure');
const digest='sha256:'+'7'.repeat(64),branch='hermes/update-e2e',oldSha='a'.repeat(40),newSha='b'.repeat(40),commitSha='c'.repeat(40);
function grant(){return {contract_version:'hermes_maintainer_scm_write_authorization_grant_v1',status:'SCM_WRITE_AUTHORIZATION_GRANTED',authorization_valid:true,intent_digest:digest,operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',branch_name:branch,approval_reference:'approval-e2e',authorization_reference:'auth-e2e',human_approval_present:true,execution_authorized:true,authorization_consumed:false,credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,blockers:[]};}
const target={operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',branch};
function input(){return {consumption_reference:'consume-e2e',attempt_reference:'attempt-e2e',capability_reference:'cap-e2e',admission_reference:'admission-e2e',path:'docs/e2e.md',current_blob_sha:oldSha,content:'updated',message:'test update-file e2e'};}
function pool(){const rows=new Map();const client={async query(sql,args){if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[]};let table;if(sql.includes('update_file_finalization'))table='finalization';else if(sql.includes('update_file_execution_outcome'))table='outcome';else if(sql.includes('attempt_ownership'))table='ownership';else table='consumption';const key=args[0];if(rows.has(table+':'+key))return {rows:[]};let row;if(table==='finalization')row={finalization_key:args[0],finalization_digest:args[1],outcome_digest:args[2],intent_digest:args[3],attempt_reference:args[4],admission_reference:args[5],repository:args[6],operation:args[7],branch:args[8],path:args[9],previous_blob_sha:args[10],new_blob_sha:args[11],commit_sha:args[12],provider_status:args[13]};else if(table==='outcome')row={outcome_key:args[0],outcome_digest:args[1],intent_digest:args[2],attempt_reference:args[3],admission_reference:args[4],repository:args[5],operation:args[6],branch:args[7],path:args[8],previous_blob_sha:args[9],new_blob_sha:args[10],commit_sha:args[11],provider_status:args[12]};else if(table==='ownership')row={ownership_key:args[0],persistence_key:args[1],intent_digest:args[2],authorization_reference:args[3],consumption_reference:args[4],attempt_reference:args[5]};else row={persistence_key:args[0],intent_digest:args[1],authorization_reference:args[2],consumption_reference:args[3]};rows.set(table+':'+key,row);return {rows:[row]};},release(){}};return {connect:async()=>client,async query(sql,args){let table;if(sql.includes('update_file_finalization'))table='finalization';else if(sql.includes('update_file_execution_outcome'))table='outcome';else if(sql.includes('attempt_ownership'))table='ownership';else table='consumption';const row=rows.get(table+':'+args[0]);return {rows:row?[row]:[]};}};}
test('closes update-file durable chain and preserves provider identity',async()=>{let calls=0,body;const out=await createHermesMaintainerGithubUpdateFileE2eDurableClosure({pool:pool(),environment:{HERMES_GITHUB_UPDATE_FILE_STAGING_TOKEN:'synthetic-token'},fetchImpl:async(_url,o)=>{calls++;body=JSON.parse(o.body);return {status:200,json:async()=>({content:{sha:newSha},commit:{sha:commitSha}})};},createTimeoutSignal:()=>new AbortController().signal}).execute(grant(),target,input());assert.equal(calls,1);assert.equal(body.sha,oldSha);assert.equal(body.branch,branch);assert.equal(out.status,'UPDATE_FILE_E2E_DURABLE_CLOSURE_CONFIRMED');assert.equal(out.closure_valid,true);assert.equal(out.durable,true);assert.equal(out.receipt.previous_blob_sha,oldSha);assert.equal(out.receipt.new_blob_sha,newSha);assert.equal(out.receipt.commit_sha,commitSha);assert.equal(out.network_call_performed,true);assert.equal(out.write_performed,true);assert.equal(out.production_used,false);});
test('replay fails closed before a second provider update',async()=>{let calls=0;const c=createHermesMaintainerGithubUpdateFileE2eDurableClosure({pool:pool(),environment:{HERMES_GITHUB_UPDATE_FILE_STAGING_TOKEN:'synthetic-token'},fetchImpl:async()=>{calls++;return {status:200,json:async()=>({content:{sha:newSha},commit:{sha:commitSha}})};},createTimeoutSignal:()=>new AbortController().signal});const first=await c.execute(grant(),target,input()),replay=await c.execute(grant(),target,input());assert.equal(first.closure_valid,true);assert.equal(replay.status,'UPDATE_FILE_E2E_DURABLE_CLOSURE_BLOCKED');assert.deepEqual(replay.blockers,['DURABLE_ADMISSION_NOT_CONFIRMED']);assert.equal(calls,1);});
test('invalid target fails closed before provider',async()=>{let calls=0;const out=await createHermesMaintainerGithubUpdateFileE2eDurableClosure({pool:pool(),environment:{HERMES_GITHUB_UPDATE_FILE_STAGING_TOKEN:'synthetic-token'},fetchImpl:async()=>{calls++;return {status:200,json:async()=>({content:{sha:newSha},commit:{sha:commitSha}})};},createTimeoutSignal:()=>new AbortController().signal}).execute(grant(),{...target,branch:'main'},input());assert.equal(out.status,'UPDATE_FILE_E2E_DURABLE_CLOSURE_BLOCKED');assert.equal(calls,0);assert.equal(out.durable,false);});
test('construction is inert and keeps update-file credential isolated',()=>{let calls=0;const c=createHermesMaintainerGithubUpdateFileE2eDurableClosure({pool:pool(),environment:{HERMES_GITHUB_UPDATE_FILE_STAGING_TOKEN:'synthetic-token'},fetchImpl:async()=>{calls++;},createTimeoutSignal:()=>new AbortController().signal});assert.equal(c.composition_version,'hermes_maintainer_github_update_file_e2e_durable_closure_v1');assert.equal(c.credential_reference,'github_update_file_hermes_branch_staging');assert.equal(calls,0);assert.equal(c.production_used,false);assert.throws(()=>createHermesMaintainerGithubUpdateFileE2eDurableClosure(),/postgres_pool_required/);});
