'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {TABLE,INSERT_SQL,SELECT_SQL,createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence}=require('../src/core/hermes-maintainer-github-write-execution-outcome-postgres-persistence');
function input(){return {key:'sha256:'+'c'.repeat(64)+'::execution-outcome',outcome_digest:'sha256:'+'c'.repeat(64),intent_digest:'sha256:'+'a'.repeat(64),attempt_reference:'attempt-1',admission_reference:'admission-1',repository:'instutodp-cpu/agente-grupo-erick',operation:'create_branch',ref:'refs/heads/hermes/canary/first-write',sha:'b'.repeat(40),provider_status:201};}
function poolFor({insertRows=[{outcome_key:input().key}],selectRows=[{outcome_key:input().key,...input()}],throwInsert=false}={}){const log=[];const client={query:async(sql,args)=>{log.push([sql,args]);if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[]};if(throwInsert)throw new Error('db secret');return {rows:insertRows};},release(){log.push(['RELEASE']);}};return {log,connect:async()=>client,query:async(sql,args)=>{log.push([sql,args]);return {rows:selectRows};}};}
test('uses fixed outcome table and atomic create-if-absent SQL',()=>{assert.equal(TABLE,'hermes.maintainer_github_write_execution_outcome');assert.match(INSERT_SQL,/ON CONFLICT \(outcome_key\) DO NOTHING RETURNING outcome_key/);assert.match(SELECT_SQL,/WHERE outcome_key=\$1/);});
test('commits then independently confirms exact persisted outcome',async()=>{const pool=poolFor();const backend=createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence({pool});const r=await backend.createIfAbsent(input());assert.deepEqual(r,{status:'CREATED',durable:true});assert.ok(pool.log.some(([sql])=>sql==='COMMIT'));assert.ok(pool.log.some(([sql])=>sql===SELECT_SQL));});
test('duplicate rolls back and is not durable',async()=>{const pool=poolFor({insertRows:[]});const r=await createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence({pool}).createIfAbsent(input());assert.deepEqual(r,{status:'EXISTS',durable:false});assert.ok(pool.log.some(([sql])=>sql==='ROLLBACK'));assert.equal(pool.log.some(([sql])=>sql===SELECT_SQL),false);});
test('invalid, mismatched confirmation, and backend failure fail closed',async()=>{const backend=createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence({pool:poolFor()});assert.deepEqual(await backend.createIfAbsent({...input(),provider_status:401}),{status:'INVALID',durable:false});const mismatch=poolFor({selectRows:[{...input(),outcome_key:input().key,sha:'d'.repeat(40)}]});assert.deepEqual(await createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence({pool:mismatch}).createIfAbsent(input()),{status:'UNCONFIRMED',durable:false});const failing=poolFor({throwInsert:true});assert.deepEqual(await createHermesMaintainerGithubWriteExecutionOutcomePostgresPersistence({pool:failing}).createIfAbsent(input()),{status:'FAILED',durable:false});});
