'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {createHermesMaintainerGithubWriteFinalizationPersistenceAdapter}=require('../src/core/hermes-maintainer-github-write-finalization-persistence-adapter');
function request(){return {contract_version:'hermes_maintainer_github_write_finalization_persistence_contract_v1',status:'GITHUB_WRITE_FINALIZATION_PERSISTENCE_REQUEST_PREPARED',request_valid:true,persistence_operation:'CREATE_IF_ABSENT',finalization_key:'sha256:'+'d'.repeat(64)+'::write-finalization',finalization_digest:'sha256:'+'d'.repeat(64),outcome_digest:'sha256:'+'c'.repeat(64),intent_digest:'sha256:'+'a'.repeat(64),attempt_reference:'attempt-1',admission_reference:'admission-1',repository:'instutodp-cpu/agente-grupo-erick',operation:'create_branch',ref:'refs/heads/hermes/canary/first-write',sha:'b'.repeat(40),provider_status:201,atomic_create_if_absent_required:true,durable_confirmation_required:true,persistence_performed:false,durable:false,network_call_performed:false,write_performed:false,production_used:false,blockers:[]};}

test('persists exact finalization identity through injected create-if-absent backend',async()=>{let input;const adapter=createHermesMaintainerGithubWriteFinalizationPersistenceAdapter({createIfAbsent:async value=>(input=value,{status:'CREATED',durable:true})});const r=await adapter.persist(request());assert.equal(r.status,'GITHUB_WRITE_FINALIZATION_PERSISTENCE_CREATED');assert.equal(r.adapter_valid,true);assert.equal(r.created,true);assert.equal(r.durable,true);assert.equal(input.key,request().finalization_key);assert.equal(input.finalization_digest,request().finalization_digest);assert.equal(input.provider_status,201);assert.equal(r.network_call_performed,false);assert.equal(r.write_performed,false);});

test('fails closed before backend for invalid request semantics',async()=>{let calls=0;const adapter=createHermesMaintainerGithubWriteFinalizationPersistenceAdapter({createIfAbsent:async()=>{calls++;return {status:'CREATED',durable:true};}});for(const patch of [{request_valid:false},{persistence_operation:'UPSERT'},{finalization_key:'wrong'},{write_performed:true},{durable:true}]){const r=await adapter.persist({...request(),...patch});assert.equal(r.adapter_valid,false);assert.equal(r.persistence_performed,false);}assert.equal(calls,0);});

test('duplicate and backend failure do not confirm durability',async()=>{const duplicate=createHermesMaintainerGithubWriteFinalizationPersistenceAdapter({createIfAbsent:async()=>({status:'EXISTS',durable:false})});const a=await duplicate.persist(request());assert.equal(a.status,'GITHUB_WRITE_FINALIZATION_PERSISTENCE_EXISTS');assert.equal(a.durable,false);const failing=createHermesMaintainerGithubWriteFinalizationPersistenceAdapter({createIfAbsent:async()=>{throw new Error('secret backend detail');}});const b=await failing.persist(request());assert.equal(b.status,'GITHUB_WRITE_FINALIZATION_PERSISTENCE_FAILED');assert.deepEqual(b.blockers,['FINALIZATION_PERSISTENCE_BACKEND_FAILED']);assert.equal(JSON.stringify(b).includes('secret backend detail'),false);});
