'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {prepareHermesMaintainerTrustedE2eApprovalRequests}=require('../src/runtime/hermes-maintainer-trusted-e2e-approval-request-preparation');
const {bindHermesMaintainerTrustedE2eHumanApprovals}=require('../src/runtime/hermes-maintainer-trusted-e2e-human-approval-binding');
const {prepareHermesMaintainerTrustedE2eAuthorizationRequests}=require('../src/runtime/hermes-maintainer-trusted-e2e-authorization-request-preparation');
const {bindHermesMaintainerTrustedE2eAuthorizationGrants}=require('../src/runtime/hermes-maintainer-trusted-e2e-authorization-grant-binding');
function requests(){const a=prepareHermesMaintainerTrustedE2eApprovalRequests({branch_name:'hermes/canary/e2e'}).approval_requests;const h={branch:{decision:'APPROVED',intent_digest:a.branch.intent_digest,approval_reference:'human:branch:1'},edit:{decision:'APPROVED',intent_digest:a.edit.intent_digest,approval_reference:'human:edit:1'},pull_request:{decision:'APPROVED',intent_digest:a.pull_request.intent_digest,approval_reference:'human:pr:1'}};const b=bindHermesMaintainerTrustedE2eHumanApprovals({approval_requests:a,decisions:h}).approval_bindings;return prepareHermesMaintainerTrustedE2eAuthorizationRequests({approval_bindings:b}).authorization_requests}
function decisions(r){return {branch:{decision:'AUTHORIZED',intent_digest:r.branch.intent_digest,authorization_reference:'control:branch:1'},edit:{decision:'AUTHORIZED',intent_digest:r.edit.intent_digest,authorization_reference:'control:edit:1'},pull_request:{decision:'AUTHORIZED',intent_digest:r.pull_request.intent_digest,authorization_reference:'control:pr:1'}}}
test('binds three external authorization decisions without consuming grants',()=>{const r=requests(),x=bindHermesMaintainerTrustedE2eAuthorizationGrants({authorization_requests:r,decisions:decisions(r)});assert.equal(x.granted,true);assert.equal(x.execution_authorized,true);assert.equal(x.authorization_consumed,false);assert.equal(x.merge_authority,false);assert.equal(x.human_merge_required,true);for(const g of Object.values(x.authorization_grants)){assert.equal(g.authorization_valid,true);assert.equal(g.execution_authorized,true);assert.equal(g.authorization_consumed,false);assert.equal(g.network_call_performed,false);assert.equal(g.write_performed,false);}});
test('fails closed when any external authorization decision is missing',()=>{const r=requests(),d=decisions(r);const partial={branch:d.branch,pull_request:d.pull_request};const x=bindHermesMaintainerTrustedE2eAuthorizationGrants({authorization_requests:r,decisions:partial});assert.equal(x.granted,false);assert.equal(x.execution_authorized,false);assert.equal(x.blockers[0],'AUTHORIZATION_DECISIONS_MISSING');});
test('fails closed on authorization digest mismatch',()=>{const r=requests(),d=decisions(r);d.edit={...d.edit,intent_digest:r.branch.intent_digest};const x=bindHermesMaintainerTrustedE2eAuthorizationGrants({authorization_requests:r,decisions:d});assert.equal(x.granted,false);assert.equal(x.authorization_consumed,false);assert.equal(x.blockers[0],'OFFICIAL_AUTHORIZATION_GRANT_INVALID');});