'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildHermesMaintainerScmWriteIntent}=require('../src/core/hermes-maintainer-scm-write-intent');
const {fingerprintHermesMaintainerScmWriteIntent}=require('../src/core/hermes-maintainer-scm-write-intent-fingerprint');
const {buildHermesMaintainerScmWriteApprovalRequest}=require('../src/core/hermes-maintainer-scm-write-approval-request');
const {bindHermesMaintainerScmWriteApproval}=require('../src/core/hermes-maintainer-scm-write-approval-binding');
const {buildHermesMaintainerScmWriteAuthorizationRequest}=require('../src/core/hermes-maintainer-scm-write-authorization-request');
const {grantHermesMaintainerScmWriteAuthorization}=require('../src/core/hermes-maintainer-scm-write-authorization-grant');
function request(){const i=buildHermesMaintainerScmWriteIntent({provider:'GITHUB',operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',branch_name:'hermes/example-change'});const f=fingerprintHermesMaintainerScmWriteIntent(i);const ar=buildHermesMaintainerScmWriteApprovalRequest(i,f);const ab=bindHermesMaintainerScmWriteApproval(ar,{decision:'APPROVED',intent_digest:ar.intent_digest,approval_reference:'human-review-1'});return buildHermesMaintainerScmWriteAuthorizationRequest(ab);}
test('grants explicit authorization bound to the exact approved intent without performing a write',()=>{const r=request();const g=grantHermesMaintainerScmWriteAuthorization(r,{decision:'AUTHORIZED',intent_digest:r.intent_digest,authorization_reference:'control-plane-1'});assert.equal(g.status,'SCM_WRITE_AUTHORIZATION_GRANTED');assert.equal(g.authorization_valid,true);assert.equal(g.execution_authorized,true);assert.equal(g.authorization_consumed,false);assert.equal(g.network_call_performed,false);assert.equal(g.write_performed,false);assert.equal(g.credential_material_present,false);});
test('fails closed when authorization targets another digest',()=>{const r=request();const g=grantHermesMaintainerScmWriteAuthorization(r,{decision:'AUTHORIZED',intent_digest:'sha256:'+'0'.repeat(64),authorization_reference:'control-plane-2'});assert.equal(g.authorization_valid,false);assert.ok(g.blockers.includes('AUTHORIZATION_DIGEST_MISMATCH'));assert.equal(g.execution_authorized,false);});
test('denied or unreferenced authorization cannot grant execution',()=>{const r=request();for(const a of [{decision:'DENIED',intent_digest:r.intent_digest,authorization_reference:'control-plane-3'},{decision:'AUTHORIZED',intent_digest:r.intent_digest,authorization_reference:''}]){const g=grantHermesMaintainerScmWriteAuthorization(r,a);assert.equal(g.authorization_valid,false);assert.equal(g.execution_authorized,false);assert.equal(g.write_performed,false);}});
