'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {admitHermesMaintainerSafeWorkflowAuthorization,validateHermesMaintainerSafeWorkflowAuthorizationAdmission}=require('../src/core/hermes-maintainer-safe-workflow-authorization-admission');
const digest='sha256:'+'a'.repeat(64),intentDigest='sha256:'+'b'.repeat(64);
function binding(o={}){return {contract_version:'hermes_maintainer_safe_workflow_intent_binding_v1',mission_id:'m1',workflow_digest:digest,intent_digest:intentDigest,action_count:7,intent_count:7,status:'MAINTAINER_SAFE_WORKFLOW_INTENT_BINDING_PREPARED_SIMULATION',binding_prepared:true,execution_eligible:false,execution_authorized:false,authority_consumed:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
function request(o={}){return {contract_version:'hermes_maintainer_execution_authorization_request_v1',mission_id:'m1',intent_fingerprint_contract_version:'hermes_maintainer_execution_intent_fingerprint_v1',intent_digest:intentDigest,intent_count:7,status:'MAINTAINER_EXECUTION_AUTHORIZATION_REQUESTED_SIMULATION',authorization_requested:true,authorization_granted:false,execution_authorized:false,authority_consumed:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
test('admits a matching authorization request without granting authority',()=>{const a=admitHermesMaintainerSafeWorkflowAuthorization(binding(),request());assert.equal(a.admitted,true);assert.equal(a.authorization_requested,true);assert.equal(a.authorization_granted,false);assert.equal(a.execution_authorized,false);assert.equal(a.merge_authority,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowAuthorizationAdmission(a),{valid:true,errors:[]});});
test('fails closed on intent digest mismatch',()=>{const a=admitHermesMaintainerSafeWorkflowAuthorization(binding(),request({intent_digest:'sha256:'+'c'.repeat(64)}));assert.equal(a.admitted,false);assert.ok(a.blockers.includes('intent_digest_mismatch'));assert.equal(a.operational_authority_consumed,false);});
test('fails closed on mission mismatch',()=>{const a=admitHermesMaintainerSafeWorkflowAuthorization(binding(),request({mission_id:'m2'}));assert.equal(a.admitted,false);assert.ok(a.blockers.includes('mission_id_mismatch'));assert.equal(a.execution_eligible,false);});
