'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {bindHermesMaintainerSafeWorkflowDurableOwnership,validateHermesMaintainerSafeWorkflowDurableOwnershipBinding}=require('../src/core/hermes-maintainer-safe-workflow-durable-ownership-binding');
const d='sha256:'+'a'.repeat(64),i='sha256:'+'b'.repeat(64),b='sha256:'+'c'.repeat(64);
function requirement(o={}){return {contract_version:'hermes_maintainer_safe_workflow_durable_ownership_requirement_v1',mission_id:'m1',workflow_digest:d,intent_digest:i,intent_count:7,authorization_binding_digest:b,workflow_operation:'branch_prepare',durable_operation:'create_branch',target_handoff_contract:'hermes_maintainer_scm_write_durable_admission_handoff_v1',required_ownership_contract:'hermes_maintainer_scm_write_durable_ownership_binding_v1',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',status:'MAINTAINER_SAFE_WORKFLOW_DURABLE_OWNERSHIP_REQUIRED_SIMULATION',ownership_requirement_ready:true,ownership_bound:false,ownership_exclusive_required:true,durable_replay_protection_required:true,execution_eligible:false,execution_authorized:false,network_authorized:false,credentials_authorized:false,write_authorized:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
function ownership(o={}){return {contract_version:'hermes_maintainer_scm_write_durable_ownership_binding_v1',status:'SCM_WRITE_DURABLE_OWNERSHIP_BOUND',binding_valid:true,ownership_source:'DURABLE_PERSISTENCE_RECEIPT',ownership_key:'persist-1::attempt-ownership',persistence_key:'persist-1',intent_digest:i,authorization_reference:'auth-1',consumption_reference:'consume-1',attempt_reference:'attempt-1',durable_replay_protection:true,ownership_exclusive:true,execution_authorized:false,credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,blockers:[],...o};}
test('binds matching durable ownership to safe workflow without authority',()=>{const x=bindHermesMaintainerSafeWorkflowDurableOwnership(requirement(),ownership());assert.equal(x.ownership_bound,true);assert.equal(x.intent_digest,i);assert.equal(x.attempt_reference,'attempt-1');assert.equal(x.execution_authorized,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowDurableOwnershipBinding(x),{valid:true,errors:[]});});
test('blocks ownership for a different intent',()=>{const x=bindHermesMaintainerSafeWorkflowDurableOwnership(requirement(),ownership({intent_digest:'sha256:'+'d'.repeat(64)}));assert.equal(x.ownership_bound,false);assert.ok(x.blockers.includes('intent_digest_mismatch'));assert.equal(x.write_authorized,false);});
test('blocks ownership side-effect drift',()=>{const x=bindHermesMaintainerSafeWorkflowDurableOwnership(requirement(),ownership({network_call_performed:true}));assert.equal(x.ownership_bound,false);assert.ok(x.blockers.includes('durable_ownership_state_invalid'));assert.equal(x.network_authorized,false);});
