'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {bridgeHermesMaintainerOperationalAuthorityEvidence}=require('../src/core/hermes-maintainer-operational-authority-evidence-bridge');
const digest='sha256:'+'1'.repeat(64);
function admission(operation='update_file',o={}){const versions={create_branch:'hermes_maintainer_github_durable_write_admission_v1',update_file:'hermes_maintainer_github_update_file_durable_admission_v1',create_pull_request:'hermes_maintainer_github_create_pull_request_durable_admission_v1'};return {contract_version:versions[operation],admission_valid:true,execution_authorized:true,operation,repository:'instutodp-cpu/agente-grupo-erick',ownership_source:'DURABLE_PERSISTENCE_RECEIPT',ownership_key:'persist::attempt-ownership',persistence_key:'persist',intent_digest:digest,attempt_reference:'attempt-1',capability_reference:'cap-1',credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,...o};}
function grant(operation='update_file',o={}){return {contract_version:'hermes_maintainer_scm_write_authorization_grant_v1',status:'SCM_WRITE_AUTHORIZATION_GRANTED',authorization_valid:true,execution_authorized:true,authorization_consumed:false,operation,repository:'instutodp-cpu/agente-grupo-erick',intent_digest:digest,approval_reference:'approval-1',authorization_reference:'auth-1',credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,...o};}

for(const op of ['create_branch','update_file','create_pull_request']) test('bridges official durable admission plus authorization grant for '+op,()=>{const x=bridgeHermesMaintainerOperationalAuthorityEvidence(admission(op),grant(op));assert.equal(x.bridge_valid,true);assert.equal(x.ownership.binding_valid,true);assert.equal(x.ownership.attempt_reference,'attempt-1');assert.equal(x.authority_evidence.intent_digest,digest);assert.equal(x.authority_evidence.approval_reference,'approval-1');assert.equal(x.authority_evidence.authorization_reference,'auth-1');assert.equal(x.production_used,false);assert.equal(x.merge_authority,false);assert.equal(x.human_merge_required,true);});

test('fails closed when durable admission and grant are for different intents',()=>{const x=bridgeHermesMaintainerOperationalAuthorityEvidence(admission(),grant('update_file',{intent_digest:'sha256:'+'2'.repeat(64)}));assert.equal(x.bridge_valid,false);assert.deepEqual(x.blockers,['AUTHORIZATION_SCOPE_MISMATCH']);});
test('fails closed without human authorization evidence',()=>{const x=bridgeHermesMaintainerOperationalAuthorityEvidence(admission(),grant('update_file',{authorization_reference:null}));assert.equal(x.bridge_valid,false);assert.deepEqual(x.blockers,['HUMAN_AUTHORIZATION_EVIDENCE_MISSING']);});
test('fails closed for side-effected preexecution admission',()=>{const x=bridgeHermesMaintainerOperationalAuthorityEvidence(admission('update_file',{write_performed:true}),grant());assert.equal(x.bridge_valid,false);assert.deepEqual(x.blockers,['ADMISSION_SIDE_EFFECT_STATE_INVALID']);});
