'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const Module=require('node:module');
function load(bridge){const o=Module._load;Module._load=function(r,p,m){if(r.endsWith('hermes-maintainer-operational-authority-evidence-bridge'))return {bridgeHermesMaintainerOperationalAuthorityEvidence:bridge};return o(r,p,m)};try{const p=require.resolve('../src/runtime/hermes-maintainer-trusted-e2e-canary-workflow-preparation');delete require.cache[p];return require(p)}finally{Module._load=o}}
const ownership={contract_version:'hermes_maintainer_scm_write_durable_ownership_binding_v1',status:'SCM_WRITE_DURABLE_OWNERSHIP_BOUND',binding_valid:true,ownership_source:'DURABLE_PERSISTENCE_RECEIPT',ownership_key:'persist::attempt-ownership',persistence_key:'persist',intent_digest:'sha256:'+'1'.repeat(64),durable_replay_protection:true,ownership_exclusive:true,execution_authorized:false,network_call_performed:false,write_performed:false,production_used:false};const evidence={decision:'GRANTED',capability:'github_create_branch_staging',intent_digest:'sha256:'+'1'.repeat(64),capability_reference:'cap-1'};
const okBridge=(a)=>({bridge_valid:true,ownership:{...ownership,attempt_reference:a.attempt_reference},authority_evidence:{...evidence,attempt_reference:a.attempt_reference}});
function input(){const branch='hermes/canary/e2e';const part=(op,target)=>({controlled_execution:{op},target,admission:{operation:op,attempt_reference:'attempt-'+op,admission_reference:'admission-'+op},grant:{operation:op},mutation_input:{op}});return {repository_read:{path:'README.md'},branch:part('create_branch',{operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',base_sha:'a'.repeat(40),branch_name:branch}),edit:part('update_file',{operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',branch}),pull_request:part('create_pull_request',{operation:'create_pull_request',repository:'instutodp-cpu/agente-grupo-erick',base:'main',head:branch,draft:true})};}
test('prepares one chained workflow from three already-authorized operational artifacts',()=>{const m=load(okBridge),x=m.prepareHermesMaintainerTrustedE2eCanaryWorkflow(input());assert.equal(x.prepared,true);assert.equal(x.workflow.branch_prepare.target.branch_name,'hermes/canary/e2e');assert.equal(x.workflow.code_edit_prepare.target.branch,'hermes/canary/e2e');assert.equal(x.workflow.pull_request_prepare.target.head,'hermes/canary/e2e');assert.equal(x.production_used,false);assert.equal(x.merge_authority,false);assert.equal(x.human_merge_required,true);});
test('bridges validated operational authority evidence into the execution capability grant',()=>{const m=load(okBridge),x=m.prepareHermesMaintainerTrustedE2eCanaryWorkflow(input());const g=x.workflow.branch_prepare.mutation_input.grant;assert.deepEqual(g,{decision:'GRANTED',capability:'github_create_branch_staging',intent_digest:'sha256:'+'1'.repeat(64),attempt_reference:'attempt-create_branch',capability_reference:'cap-1'});assert.equal('authorization_reference' in g,false);});
test('fails closed when any authority bridge is invalid',()=>{let n=0;const m=load(()=>{n++;return n===2?{bridge_valid:false,status:'BLOCKED'}:{bridge_valid:true,ownership,authority_evidence:evidence}}),x=m.prepareHermesMaintainerTrustedE2eCanaryWorkflow(input());assert.equal(x.prepared,false);assert.equal(x.stage,'edit_authority_bridge');assert.equal(n,2);});
test('fails closed when mutation targets do not form one branch chain',()=>{const m=load(okBridge),i=input();i.edit.target.branch='hermes/canary/other';const x=m.prepareHermesMaintainerTrustedE2eCanaryWorkflow(i);assert.equal(x.prepared,false);assert.equal(x.stage,'workflow_target_chain_invalid');});
test('does not expose execution or authorization grant operations',()=>{const m=load(okBridge);assert.equal(typeof m.execute,'undefined');assert.equal(typeof m.authorize,'undefined');assert.equal(typeof m.grantAuthority,'undefined');});