'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {bindHermesMaintainerSafeWorkflowAuthorization,validateHermesMaintainerSafeWorkflowAuthorizationBinding}=require('../src/core/hermes-maintainer-safe-workflow-authorization-binding');
const {buildHermesMaintainerAuthorizationBinding}=require('../src/core/hermes-maintainer-authorization-binding');
const d='sha256:'+'a'.repeat(64),i='sha256:'+'b'.repeat(64);
function admission(o={}){return {contract_version:'hermes_maintainer_safe_workflow_authorization_admission_v1',mission_id:'m1',workflow_digest:d,intent_digest:i,intent_count:7,status:'MAINTAINER_SAFE_WORKFLOW_AUTHORIZATION_ADMITTED_SIMULATION',admitted:true,authorization_requested:true,authorization_granted:false,execution_eligible:false,execution_authorized:false,authority_consumed:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
function request(o={}){return {contract_version:'hermes_maintainer_execution_authorization_request_v1',mission_id:'m1',intent_fingerprint_contract_version:'hermes_maintainer_execution_intent_fingerprint_v1',intent_digest:i,intent_count:7,status:'MAINTAINER_EXECUTION_AUTHORIZATION_REQUESTED_SIMULATION',authorization_requested:true,authorization_granted:false,execution_authorized:false,authority_consumed:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
test('binds admitted safe workflow to verified authorization binding without authority',()=>{const r=request(),b=buildHermesMaintainerAuthorizationBinding(r),x=bindHermesMaintainerSafeWorkflowAuthorization(admission(),r,b);assert.equal(x.binding_prepared,true);assert.equal(x.authorization_granted,false);assert.equal(x.execution_authorized,false);assert.equal(x.merge_authority,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowAuthorizationBinding(x),{valid:true,errors:[]});});
test('fails closed when admission mission differs',()=>{const r=request(),b=buildHermesMaintainerAuthorizationBinding(r),x=bindHermesMaintainerSafeWorkflowAuthorization(admission({mission_id:'m2'}),r,b);assert.equal(x.binding_prepared,false);assert.ok(x.blockers.includes('mission_id_mismatch'));assert.equal(x.operational_authority_consumed,false);});
test('fails closed when intent count differs',()=>{const r=request(),b=buildHermesMaintainerAuthorizationBinding(r),x=bindHermesMaintainerSafeWorkflowAuthorization(admission({intent_count:6}),r,b);assert.equal(x.binding_prepared,false);assert.ok(x.blockers.includes('intent_count_mismatch'));assert.equal(x.execution_eligible,false);});
