'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildHermesMaintainerExecutionAttemptClaim}=require('../src/core/hermes-maintainer-execution-attempt-ownership');
const {buildHermesMaintainerDurableAdmissionHandoff,validateHermesMaintainerDurableAdmissionHandoff}=require('../src/core/hermes-maintainer-durable-admission-handoff');
const consumption={ok:true,status:'CONSUMED',authorization_id:'a1',fingerprint:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'};
const input={attempt_id:'at1',mission_id:'m1',operation:'repository_read',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',executor_id:'hermes-maintainer-staging',lease_id:'lease1',lease_expires_at:'2026-09-24T22:00:00.000Z',idempotency_key:'idem1'};
const attempt=()=>buildHermesMaintainerExecutionAttemptClaim(consumption,input);
test('prepares durable admission handoff without execution eligibility',()=>{const v=buildHermesMaintainerDurableAdmissionHandoff(attempt(),{admission_id:'adm1'});assert.equal(v.admission_prepared,true);assert.equal(v.execution_eligible,false);assert.equal(v.execution_performed,false);assert.equal(validateHermesMaintainerDurableAdmissionHandoff(v).valid,true);});
test('blocked attempt fails closed',()=>{const bad=buildHermesMaintainerExecutionAttemptClaim({ok:false,status:'INVALID'},input);assert.equal(buildHermesMaintainerDurableAdmissionHandoff(bad,{admission_id:'adm1'}).admission_prepared,false);});
test('handoff fingerprint drift is rejected',()=>{const v={...buildHermesMaintainerDurableAdmissionHandoff(attempt(),{admission_id:'adm1'}),repository:'other'};assert.equal(validateHermesMaintainerDurableAdmissionHandoff(v).valid,false);});
test('validator rejects execution eligibility',()=>{const v={...buildHermesMaintainerDurableAdmissionHandoff(attempt(),{admission_id:'adm1'}),execution_eligible:true};assert.equal(validateHermesMaintainerDurableAdmissionHandoff(v).valid,false);});
