'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {prepareHermesMaintainerTrustedE2eApprovalRequests}=require('../src/runtime/hermes-maintainer-trusted-e2e-approval-request-preparation');
const {bindHermesMaintainerTrustedE2eHumanApprovals}=require('../src/runtime/hermes-maintainer-trusted-e2e-human-approval-binding');
const {prepareHermesMaintainerTrustedE2eAuthorizationRequests}=require('../src/runtime/hermes-maintainer-trusted-e2e-authorization-request-preparation');
const {prepareHermesMaintainerTrustedE2eAuthorizedOperational}=require('../src/runtime/hermes-maintainer-trusted-e2e-authorized-operational-composition');
const branch='hermes/canary/e2e';
function decisions(){const a=prepareHermesMaintainerTrustedE2eApprovalRequests({branch_name:branch}).approval_requests;const human={branch:{decision:'APPROVED',intent_digest:a.branch.intent_digest,approval_reference:'human:branch:1'},edit:{decision:'APPROVED',intent_digest:a.edit.intent_digest,approval_reference:'human:edit:1'},pull_request:{decision:'APPROVED',intent_digest:a.pull_request.intent_digest,approval_reference:'human:pr:1'}};const b=bindHermesMaintainerTrustedE2eHumanApprovals({approval_requests:a,decisions:human}).approval_bindings;const r=prepareHermesMaintainerTrustedE2eAuthorizationRequests({approval_bindings:b}).authorization_requests;return {human,authorization:{branch:{decision:'AUTHORIZED',intent_digest:r.branch.intent_digest,authorization_reference:'control:branch:1'},edit:{decision:'AUTHORIZED',intent_digest:r.edit.intent_digest,authorization_reference:'control:edit:1'},pull_request:{decision:'AUTHORIZED',intent_digest:r.pull_request.intent_digest,authorization_reference:'control:pr:1'}}}}
test('fails closed before durable consumption when operational evidence is incomplete',()=>{const d=decisions(),x=prepareHermesMaintainerTrustedE2eAuthorizedOperational({branch_name:branch,human_decisions:d.human,authorization_decisions:d.authorization,operational_evidence:{}});assert.equal(x.prepared,false);assert.equal(x.stage,'operational_input');assert.equal(x.authorization_consumed,false);assert.equal(x.merge_authority,false);});
test('fails closed before grants when external authorization decision is missing',()=>{const d=decisions(),partial={branch:d.authorization.branch,edit:d.authorization.edit};const x=prepareHermesMaintainerTrustedE2eAuthorizedOperational({branch_name:branch,human_decisions:d.human,authorization_decisions:partial,operational_evidence:{}});assert.equal(x.prepared,false);assert.equal(x.stage,'authorization_grants');assert.equal(x.authorization_consumed,false);});