'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {TABLE,INSERT_SQL,SELECT_SQL,createHermesMaintainerGithubWriteFinalizationPostgresPersistence}=require('../src/core/hermes-maintainer-github-write-finalization-postgres-persistence');
function input(){return {key:'sha256:'+'d'.repeat(64)+'::write-finalization',finalization_digest:'sha256:'+'d'.repeat(64),outcome_digest:'sha256:'+'c'.repeat(64),intent_digest:'sha256:'+'a'.repeat(64),attempt_reference:'attempt-1',admission_reference:'admission-1',repository:'instutodp-cpu/agente-grupo-erick',operation:'create_branch',ref:'refs/heads/hermes/canary/first-write',sha:'b'.repeat(40),provider_status:201};}
function row(){const i=input();return {finalization_key:i.key,finalization_digest:i.finalization_digest,outcome_digest:i.outcome_digest,intent_digest:i.intent_digest,attempt_reference:i.attempt_reference,admission_reference:i.admission_reference,repository:i.repository,operation:i.operation,ref:i.ref,sha:i.sha,provider_status:i.provider_status};}
function poolFor({insertRows=[{finalization_key:input().key}],selectRows=[row()],throwInsert=false}={}){const log=[];const client={query:async(sql,args)=>{log.push([sql,args]);if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[]};if(throwInsert)throw new Error('db secret');if(sql===SELECT_SQL)return {rows:selectRows};return {rows:insertRows};},release(){log.push(['RELEASE']);}};return {log,connect:async()=>client,query:async(sql,args)=>{log.push([sql,args]);return {rows:selectRows};}};}

test('uses fixed finalization table and atomic create-if-absent SQL',()=>{assert.equal(TABLE,'hermes.maintainer_github_write_finalization');assert.match(INSERT_SQL,/ON CONFLICT \(finalization_key\) DO NOTHING RETURNING finalization_key/);assert.match(SELECT_SQL,/WHERE finalization_key=\$1/);});

test('commits then independently confirms exact persisted finalization',async()=>{const pool=poolFor();const backend=createHermesMaintainerGithubWriteFinalizationPostgresPersistence({pool});const r=await backend.createIfAbsent(input());assert.deepEqual(r,{status:'CREATED',durable:true});assert.ok(pool.log.some(([sql])=>sql==='COMMIT'));assert.ok(pool.log.some(([sql])=>sql===SELECT_SQL));});

test('duplicate rolls back and is not durable',async()=>{const pool=poolFor({insertRows:[]});const r=await createHermesMaintainerGithubWriteFinalizationPostgresPersistence({pool}).createIfAbsent(input());assert.deepEqual(r,{status:'EXISTS',durable:false});assert.ok(pool.log.some(([sql])=>sql==='ROLLBACK'));assert.equal(pool.log.some(([sql])=>sql===SELECT_SQL),false);});

test('invalid, mismatched confirmation, and backend failure fail closed',async()=>{const backend=createHermesMaintainerGithubWriteFinalizationPostgresPersistence({pool:poolFor()});assert.deepEqual(await backend.createIfAbsent({...input(),provider_status:401}),{status:'INVALID',durable:false});const mismatch=poolFor({selectRows:[{...row(),sha:'e'.repeat(40)}]});assert.deepEqual(await createHermesMaintainerGithubWriteFinalizationPostgresPersistence({pool:mismatch}).createIfAbsent(input()),{status:'UNCONFIRMED',durable:false});const failing=poolFor({throwInsert:true});assert.deepEqual(await createHermesMaintainerGithubWriteFinalizationPostgresPersistence({pool:failing}).createIfAbsent(input()),{status:'FAILED',durable:false});});
