'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {bindHermesMaintainerSafeWorkflowExecutionHandoff,validateHermesMaintainerSafeWorkflowExecutionHandoff}=require('../src/core/hermes-maintainer-safe-workflow-execution-handoff');
const d='sha256:'+'a'.repeat(64),i='sha256:'+'b'.repeat(64),b='sha256:'+'c'.repeat(64);
function safe(o={}){return {contract_version:'hermes_maintainer_safe_workflow_authorization_binding_v1',mission_id:'m1',workflow_digest:d,intent_digest:i,intent_count:7,authorization_binding_digest:b,status:'MAINTAINER_SAFE_WORKFLOW_AUTHORIZATION_BINDING_PREPARED_SIMULATION',binding_prepared:true,authorization_granted:false,execution_eligible:false,execution_authorized:false,authority_consumed:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
function handoff(o={}){return {contract_version:'hermes_maintainer_execution_handoff_adapter_v1',mission_id:'m1',source_binding_contract_version:'hermes_maintainer_authorization_binding_v1',binding_digest:b,intent_digest:i,intent_count:7,status:'MAINTAINER_EXECUTION_HANDOFF_PREPARED_SIMULATION',handoff_prepared:true,execution_eligible:false,execution_authorized:false,authority_consumed:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[],...o};}
test('binds safe workflow to prepared execution handoff without authority',()=>{const x=bindHermesMaintainerSafeWorkflowExecutionHandoff(safe(),handoff());assert.equal(x.handoff_prepared,true);assert.equal(x.execution_authorized,false);assert.equal(x.merge_authority,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowExecutionHandoff(x),{valid:true,errors:[]});});
test('fails closed when authorization binding digest differs',()=>{const x=bindHermesMaintainerSafeWorkflowExecutionHandoff(safe(),handoff({binding_digest:'sha256:'+'d'.repeat(64)}));assert.equal(x.handoff_prepared,false);assert.ok(x.blockers.includes('authorization_binding_digest_mismatch'));assert.equal(x.operational_authority_consumed,false);});
test('fails closed when mission differs',()=>{const x=bindHermesMaintainerSafeWorkflowExecutionHandoff(safe(),handoff({mission_id:'m2'}));assert.equal(x.handoff_prepared,false);assert.ok(x.blockers.includes('mission_id_mismatch'));assert.equal(x.execution_eligible,false);});
