'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {createHermesMaintainerGithubUpdateFileTransport}=require('../src/core/hermes-maintainer-github-update-file-transport');
const auth={ok:true,authorization:'Bearer synthetic'};const signal=()=>new AbortController().signal;
const req=()=>({method:'PUT',url:'https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/docs/a.md',body:{message:'docs: controlled change',content:'eA==',sha:'a'.repeat(40),branch:'hermes/content-write'},intent_digest:'sha256:'+'1'.repeat(64),attempt_reference:'attempt-1',capability_reference:'cap-1',admission_reference:'admission-1'});
const make=(fetchImpl=async()=>({status:200,json:async()=>({content:{sha:'b'.repeat(40)},commit:{sha:'c'.repeat(40)}})}),resolveAuthorization=async()=>auth)=>createHermesMaintainerGithubUpdateFileTransport({fetchImpl,resolveAuthorization,createTimeoutSignal:signal});
test('uses exact PUT request and confirms only HTTP 200',async()=>{let seen;const r=await make(async(url,o)=>{seen={url,o};return {status:200,json:async()=>({content:{sha:'b'.repeat(40)},commit:{sha:'c'.repeat(40)}})};}).updateFile(req());assert.equal(r.status,'UPDATED');assert.equal(r.updated,true);assert.equal(r.provider_status,200);assert.equal(r.new_blob_sha,'b'.repeat(40));assert.equal(r.commit_sha,'c'.repeat(40));assert.equal(r.network_call_performed,true);assert.equal(r.write_performed,false);assert.equal(seen.o.method,'PUT');assert.deepEqual(JSON.parse(seen.o.body),req().body);});
test('rejects unsafe scope before fetch',async()=>{for(const patch of [{url:'https://api.github.com/repos/other/repo/contents/a'},{body:{...req().body,branch:'main'}},{body:{...req().body,sha:'bad'}},{extra:true}]){let calls=0;const r=await make(async()=>{calls++;return {status:200};}).updateFile({...req(),...patch});assert.equal(calls,0);assert.equal(r.status,'BLOCKED');}});
test('missing authorization blocks before fetch',async()=>{let calls=0;const r=await make(async()=>{calls++;return {status:200};},async()=>null).updateFile(req());assert.equal(calls,0);assert.equal(r.reason,'AUTHORIZATION_UNAVAILABLE');});
test('non-200 never confirms update and response body is not copied',async()=>{for(const status of [201,401,403,404,409,422,500]){const r=await make(async()=>({status,body:'secret'})).updateFile(req());assert.equal(r.updated,false);assert.equal(r.status,'FAILED');assert.equal(r.provider_status,status);assert.equal(r.response_body_present,false);}});
test('transport has no credential material or production use',async()=>{const r=await make().updateFile(req());assert.equal(r.credential_material_present,false);assert.equal(r.production_used,false);assert.equal(JSON.stringify(r).includes('synthetic'),false);});

test('rejects path traversal query fragment and encoded traversal before fetch',async()=>{for(const url of ['https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/../secret','https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/docs/%2e%2e/secret','https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/docs/a.md?ref=main','https://api.github.com/repos/instutodp-cpu/agente-grupo-erick/contents/docs/a.md#x']){let calls=0;const r=await make(async()=>{calls++;return {status:200};}).updateFile({...req(),url});assert.equal(calls,0);assert.equal(r.status,'BLOCKED');}});
