'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {buildHermesMaintainerGithubWriteExecutionOutcomeReceipt}=require('../src/core/hermes-maintainer-github-write-execution-outcome-receipt');
function admission(){return {contract_version:'hermes_maintainer_github_durable_write_admission_v1',status:'GITHUB_DURABLE_WRITE_REQUEST_ADMITTED',admission_valid:true,execution_authorized:true,provider:'GITHUB',operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',intent_digest:'sha256:'+'a'.repeat(64),attempt_reference:'attempt-1',capability_reference:'capability-1',admission_reference:'admission-1',persistence_key:'sha256:'+'a'.repeat(64)+'::authorization-1',ownership_key:'sha256:'+'a'.repeat(64)+'::authorization-1::attempt-ownership',request:{body:{ref:'refs/heads/hermes/canary/first-write',sha:'b'.repeat(40)}}};}
function execution(){return {contract_version:'hermes_maintainer_github_durable_write_execution_boundary_v1',status:'GITHUB_DURABLE_WRITE_EXECUTION_SUCCEEDED',execution_performed:true,network_call_performed:true,write_performed:true,production_used:false,provider_status:201,blockers:[]};}
test('prepares deterministic non-durable outcome receipt for confirmed create-branch execution',()=>{const a=buildHermesMaintainerGithubWriteExecutionOutcomeReceipt(admission(),execution());const b=buildHermesMaintainerGithubWriteExecutionOutcomeReceipt(admission(),execution());assert.equal(a.status,'GITHUB_WRITE_EXECUTION_OUTCOME_RECEIPT_PREPARED');assert.equal(a.receipt_valid,true);assert.equal(a.provider_status,201);assert.equal(a.write_performed,true);assert.equal(a.durable,false);assert.equal(a.outcome_digest,b.outcome_digest);assert.match(a.outcome_digest,/^sha256:[a-f0-9]{64}$/);assert.equal(a.ref,'refs/heads/hermes/canary/first-write');assert.equal(a.sha,'b'.repeat(40));});
test('fails closed unless official execution confirms the write',()=>{for(const patch of [{status:'GITHUB_DURABLE_WRITE_EXECUTION_FAILED'},{write_performed:false},{provider_status:401},{network_call_performed:false},{blockers:['x']}]){const r=buildHermesMaintainerGithubWriteExecutionOutcomeReceipt(admission(),{...execution(),...patch});assert.equal(r.receipt_valid,false);assert.equal(r.outcome_digest,null);assert.equal(r.write_performed,false);assert.deepEqual(r.blockers,['EXECUTION_NOT_CONFIRMED']);}});
test('fails closed for admission identity or scope mismatch',()=>{for(const mutate of [a=>{a.repository='other/repo';},a=>{a.request.body.ref='refs/heads/main';},a=>{a.request.body.sha='bad';},a=>{a.attempt_reference='';}]){const a=admission();mutate(a);const r=buildHermesMaintainerGithubWriteExecutionOutcomeReceipt(a,execution());assert.equal(r.receipt_valid,false);assert.equal(r.outcome_digest,null);assert.equal(r.write_performed,false);}});
