'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {evaluateHermesMaintainerStagingGate,validateHermesMaintainerStagingGate}=require('../src/core/hermes-maintainer-staging-gate');
const {buildHermesMaintainerExecutionReceipt}=require('../src/core/hermes-maintainer-execution-receipt-reconciliation');
function execution(){return{contract_version:'hermes_maintainer_controlled_executor_v1',mission_id:'m1',operation:'repository_read',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',status:'MAINTAINER_CONTROLLED_EXECUTION_PREPARED_SIMULATION',execution_prepared:true,execution_eligible:false,execution_authorized:false,network_authorized:false,credentials_authorized:false,write_authorized:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[]};}
test('passes staging gate only for reconciled zero-effect chain',()=>{const e=execution(),r=buildHermesMaintainerExecutionReceipt(e),g=evaluateHermesMaintainerStagingGate(e,r);assert.equal(g.staging_gate_passed,true);assert.equal(g.real_execution_enabled,false);assert.equal(validateHermesMaintainerStagingGate(g).valid,true);});
test('receipt drift blocks staging gate',()=>{const e=execution(),r=buildHermesMaintainerExecutionReceipt(e),g=evaluateHermesMaintainerStagingGate({...e,base_ref:'drift'},r);assert.equal(g.staging_gate_passed,false);});
test('claimed execution blocks staging gate',()=>{const e={...execution(),executed:true},r=buildHermesMaintainerExecutionReceipt(execution()),g=evaluateHermesMaintainerStagingGate(e,r);assert.equal(g.staging_gate_passed,false);});
test('validator rejects real execution enablement',()=>{const e=execution(),g=evaluateHermesMaintainerStagingGate(e,buildHermesMaintainerExecutionReceipt(e));assert.equal(validateHermesMaintainerStagingGate({...g,real_execution_enabled:true}).valid,false);});
