'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const {routeHermesMaintainerSafeWorkflowDurableHandoff,validateHermesMaintainerSafeWorkflowDurableHandoffRouting}=require('../src/core/hermes-maintainer-safe-workflow-durable-handoff-routing');
const d='sha256:'+'a'.repeat(64),i='sha256:'+'b'.repeat(64),a='sha256:'+'c'.repeat(64);
function ownership(o={}){return {contract_version:'hermes_maintainer_scm_write_durable_ownership_binding_v1',status:'SCM_WRITE_DURABLE_OWNERSHIP_BOUND',binding_valid:true,ownership_source:'DURABLE_PERSISTENCE_RECEIPT',ownership_key:'p::attempt-ownership',persistence_key:'p',intent_digest:i,authorization_reference:'auth',consumption_reference:'consume',attempt_reference:'attempt-1',durable_replay_protection:true,ownership_exclusive:true,execution_authorized:false,credential_material_present:false,network_call_performed:false,write_performed:false,production_used:false,blockers:[],...o};}
function prepared(op,target,handoff){return {contract_version:'hermes_maintainer_safe_workflow_durable_target_v1',mission_id:'m1',workflow_digest:d,intent_digest:i,authorization_binding_digest:a,durable_operation:op,target_handoff_contract:handoff,ownership_key:'p::attempt-ownership',attempt_reference:'attempt-1',status:'MAINTAINER_SAFE_WORKFLOW_DURABLE_TARGET_PREPARED_SIMULATION',target_prepared:true,target,execution_eligible:false,execution_authorized:false,network_authorized:false,credentials_authorized:false,write_authorized:false,merge_authority:false,human_merge_required:true,simulation:true,production_allowed:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[]};}
test('routes all official durable handoffs without execution authority',()=>{const cases=[prepared('create_branch',{operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',base_sha:'a'.repeat(40),branch_name:'hermes/next'},'hermes_maintainer_scm_write_durable_admission_handoff_v1'),prepared('update_file',{operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',branch:'hermes/next'},'hermes_maintainer_github_update_file_durable_admission_handoff_v1'),prepared('create_pull_request',{operation:'create_pull_request',repository:'instutodp-cpu/agente-grupo-erick',base:'main',head:'hermes/next',draft:true},'hermes_maintainer_github_create_pull_request_durable_admission_handoff_v1')];for(const p of cases){const x=routeHermesMaintainerSafeWorkflowDurableHandoff(p,ownership());assert.equal(x.handoff_routed,true);assert.equal(x.handoff.handoff_valid,true);assert.equal(x.execution_authorized,false);assert.equal(x.handoff.execution_authorized,false);assert.deepEqual(validateHermesMaintainerSafeWorkflowDurableHandoffRouting(x),{valid:true,errors:[]});}});
test('blocks mismatched ownership identity',()=>{const p=prepared('update_file',{operation:'update_file',repository:'instutodp-cpu/agente-grupo-erick',branch:'hermes/next'},'hermes_maintainer_github_update_file_durable_admission_handoff_v1');const x=routeHermesMaintainerSafeWorkflowDurableHandoff(p,ownership({attempt_reference:'attempt-other'}));assert.equal(x.handoff_routed,false);assert.ok(x.blockers.includes('ownership_identity_mismatch'));assert.equal(x.handoff,null);});
test('blocks handoff contract drift',()=>{const p=prepared('create_branch',{operation:'create_branch',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main',base_sha:'a'.repeat(40),branch_name:'hermes/next'},'wrong_contract');const x=routeHermesMaintainerSafeWorkflowDurableHandoff(p,ownership());assert.equal(x.handoff_routed,false);assert.ok(x.blockers.includes('handoff_contract_mismatch'));assert.equal(x.write_authorized,false);});
