'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {prepareHermesMaintainerControlledExecution,validateHermesMaintainerControlledExecution}=require('../src/core/hermes-maintainer-controlled-executor');
const {buildHermesMaintainerScmAdapterRequest}=require('../src/core/hermes-maintainer-scm-adapter-contract');
function handoff(){return{contract_version:'hermes_maintainer_execution_handoff_adapter_v1',mission_id:'m1',source_binding_contract_version:'hermes_maintainer_authorization_binding_v1',binding_digest:'sha256:'+'a'.repeat(64),intent_digest:'sha256:'+'b'.repeat(64),intent_count:1,status:'MAINTAINER_EXECUTION_HANDOFF_PREPARED_SIMULATION',handoff_prepared:true,execution_eligible:false,execution_authorized:false,authority_consumed:false,simulation:true,production_allowed:false,executed:false,runtime_mutated:false,network_used:false,provider_called:false,secret_accessed:false,operational_authority_consumed:false,blockers:[]};}
test('prepares controlled executor boundary without execution',()=>{const s=buildHermesMaintainerScmAdapterRequest({operation:'repository_read',repository:'instutodp-cpu/agente-grupo-erick',base_ref:'main'}),r=prepareHermesMaintainerControlledExecution(handoff(),s);assert.equal(r.execution_prepared,true);assert.equal(validateHermesMaintainerControlledExecution(r).valid,true);assert.equal(r.executed,false);assert.equal(r.execution_authorized,false);assert.equal(r.network_used,false);});
test('blocked SCM request fails closed',()=>{const s=buildHermesMaintainerScmAdapterRequest({operation:'push_force',repository:'repo',base_ref:'main'}),r=prepareHermesMaintainerControlledExecution(handoff(),s);assert.equal(r.execution_prepared,false);assert.equal(r.status,'MAINTAINER_CONTROLLED_EXECUTION_BLOCKED');});
test('premature authority fails closed',()=>{const s={...buildHermesMaintainerScmAdapterRequest({operation:'repository_read',repository:'repo',base_ref:'main'}),write_authorized:true},r=prepareHermesMaintainerControlledExecution(handoff(),s);assert.equal(r.execution_prepared,false);});
test('validator rejects claimed execution',()=>{const s=buildHermesMaintainerScmAdapterRequest({operation:'repository_read',repository:'repo',base_ref:'main'}),r=prepareHermesMaintainerControlledExecution(handoff(),s);assert.equal(validateHermesMaintainerControlledExecution({...r,executed:true}).valid,false);});
