'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const Module=require('node:module');
function load(fail){const original=Module._load;const calls=[];Module._load=function(r,p,m){if(r.endsWith('github-write-operational-admission-composition'))return {preflightHermesMaintainerGithubWriteOperationalAdmission:()=>fail==='branch_preflight'?{admission_preflight_valid:false}:{admission_preflight_valid:true},createHermesMaintainerGithubWriteOperationalAdmissionComposition:()=>({prepare:async()=>{calls.push('branch');return fail==='branch'?{admission_valid:false}:{admission_valid:true,operation:'create_branch'}}})};if(r.endsWith('github-update-file-operational-admission-composition'))return {preflightHermesMaintainerGithubUpdateFileOperationalAdmission:()=>fail==='edit_preflight'?{admission_preflight_valid:false}:{admission_preflight_valid:true},createHermesMaintainerGithubUpdateFileOperationalAdmissionComposition:()=>({prepare:async()=>{calls.push('edit');return fail==='edit'?{admission_valid:false}:{admission_valid:true,operation:'update_file'}}})};if(r.endsWith('github-create-pull-request-operational-admission-composition'))return {preflightHermesMaintainerGithubCreatePullRequestOperationalAdmission:()=>fail==='pull_preflight'?{admission_preflight_valid:false}:{admission_preflight_valid:true},createHermesMaintainerGithubCreatePullRequestOperationalAdmissionComposition:()=>({prepare:async()=>{calls.push('pull');return fail==='pull'?{admission_valid:false}:{admission_valid:true,operation:'create_pull_request'}}})};if(r.endsWith('trusted-e2e-canary-workflow-preparation'))return {prepareHermesMaintainerTrustedE2eCanaryWorkflow:()=>{calls.push('workflow');return fail==='workflow'?{prepared:false}:{prepared:true,workflow:{ok:true}}}};return original(r,p,m)};try{const path=require.resolve('../src/runtime/hermes-maintainer-trusted-e2e-operational-preparation');delete require.cache[path];return {m:require(path),calls}}finally{Module._load=original}}
const valid=()=>({branch:{target:{operation:'create_branch',branch_name:'hermes/canary/e2e'}},edit:{target:{operation:'update_file',branch:'hermes/canary/e2e'}},pull_request:{target:{operation:'create_pull_request',head:'hermes/canary/e2e',base:'main',draft:true}}});
test('prepares admissions in mutation order then workflow without executing canary',async()=>{const {m,calls}=load();const c=m.createHermesMaintainerTrustedE2eOperationalPreparation({pool:{}});const x=await c.prepare(valid());assert.equal(x.prepared,true);assert.deepEqual(calls,['branch','edit','pull','workflow']);assert.equal(x.production_used,false);assert.equal(x.merge_authority,false);assert.equal(x.human_merge_required,true);assert.equal(typeof c.execute,'undefined');});
for(const stage of ['branch','edit','pull','workflow'])test('fails closed at '+stage,async()=>{const {m,calls}=load(stage);const x=await m.createHermesMaintainerTrustedE2eOperationalPreparation({pool:{}}).prepare(valid());assert.equal(x.prepared,false);if(stage==='branch')assert.deepEqual(calls,['branch']);if(stage==='edit')assert.deepEqual(calls,['branch','edit']);if(stage==='pull')assert.deepEqual(calls,['branch','edit','pull']);if(stage==='workflow')assert.deepEqual(calls,['branch','edit','pull','workflow']);});

test('rejects inconsistent target chain before consuming any durable authorization',async()=>{const {m,calls}=load();const i=valid();i.edit.target.branch='hermes/canary/other';const x=await m.createHermesMaintainerTrustedE2eOperationalPreparation({pool:{}}).prepare(i);assert.equal(x.prepared,false);assert.equal(x.stage,'workflow_target_preflight');assert.deepEqual(calls,[]);});

test('rejects any invalid admission preflight before consuming durable authorization',async()=>{for(const stage of ['branch_preflight','edit_preflight','pull_preflight']){const {m,calls}=load(stage);const x=await m.createHermesMaintainerTrustedE2eOperationalPreparation({pool:{}}).prepare(valid());assert.equal(x.prepared,false);assert.equal(x.stage,'operational_admission_preflight');assert.deepEqual(calls,[]);}});