'use strict';
const assert=require('node:assert/strict'); const test=require('node:test');
const {createPublicWebCanaryOperationalPostgresBootstrap}=require('../src/pilots/public-web-canary-operational-postgres-bootstrap');
class Pool { constructor(config){this.config=config;this.ended=0;} async query(sql){ if(String(sql).includes('information_schema')) return {rows:[{schema_exists:true,table_exists:true,columns_exist:true}]}; throw new Error('unexpected'); } async end(){this.ended++;} connect(){throw new Error('not used');} }
function runtime(){return {singleUseIdFactory:(()=>{let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`;})(),operationalBootstrapConfigured:true,stagingRealTransportOptIn:true,environment:'staging',production:false,production_allowed:false,maximum_requests:1,rollout_percentage:1,
 featureFlagResolver:async()=>true,killSwitchResolver:async()=>false,
 ...Object.fromEntries(['canarySessionRegistry','targetAllowlist','adapterRegistry','lifecycleRegistry','configurationRegistry','secretReferenceRegistry','secretResolver','readinessResult','rateLimitBudget','costBudget','operatorPolicy'].map(k=>[k,{}])),clock:()=>new Date()};}
const env={POSTGRES_PORT:'5432',POSTGRES_USER:'u',POSTGRES_PASSWORD:'opaque',POSTGRES_DB:'d',HERMES_PUBLIC_WEB_REAL_CANARY_ENABLED:'true',HERMES_PUBLIC_WEB_REAL_CANARY_KILL_SWITCH:'false'};
test('composes official durable audit without exposing credential material',async()=>{const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:Pool,runtime:runtime()});assert.equal(c.bootstrap.ok,true);assert.equal(c.bootstrap.auditSink.durable,true);assert.equal(c.bootstrap.requireDurableAudit,true);assert.equal(c.credential_material_present,false);assert.equal(await c.bootstrap.featureFlagResolver(),true);assert.equal(await c.bootstrap.killSwitchResolver(),false);assert.equal(JSON.stringify(c).includes('POSTGRES_PASSWORD'),false);assert.equal(Object.prototype.hasOwnProperty.call(c,'password'),false);assert.equal(Object.prototype.hasOwnProperty.call(c,'token'),false);assert.deepEqual(await c.bootstrap.auditSink.ensureReady(),{ok:true,status:'READY'});await c.close();await c.close();});
test('fails closed before pool creation when postgres environment is incomplete',()=>{let made=0;class P extends Pool{constructor(x){super(x);made++;}}assert.throws(()=>createPublicWebCanaryOperationalPostgresBootstrap({environment:{POSTGRES_PORT:'5432'},PoolClass:P,runtime:runtime()}),/postgres_environment_invalid/);assert.equal(made,0);});
test('production-shaped runtime remains blocked by staging bootstrap',()=>{const r=runtime();r.production_allowed=true;const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:Pool,runtime:r});assert.equal(c.bootstrap.ok,false);assert.equal(c.bootstrap.blocked_reason,'production_blocked');});
test('exposes bounded email preparation without confirmation or execution reachability',async()=>{const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:Pool,runtime:runtime()});assert.equal(typeof c.prepareEmailReauthExecution,'function');const r=c.prepareEmailReauthExecution({});assert.equal(r.ok,false);assert.equal(r.execution_authorized,false);assert.equal(r.external_network_called,false);assert.equal(r.production_allowed,false);assert.equal(Object.hasOwn(c,'activation_confirmation'),false);assert.equal(Object.hasOwn(c,'runner'),false);assert.equal(c.network_call_performed,false);await c.close();});
test('resumes verified durable email evidence without recreating it or exposing execution',async()=>{let creates=0;class P extends Pool{connect(){return {query:async(sql,args)=>{if(String(sql).includes('SELECT evidence_key'))return {rowCount:1,rows:[{evidence_key:'sha256:'+ 'e'.repeat(64),challenge_id:'sha256:'+ 'c'.repeat(64),subject_id:'human:owner',action_digest:require('../src/core/canonical-content-digest').computeCanonicalContentDigest({environment:'staging',target_origin:'https://staging.example.org',target_path:'/health',method:'GET',port:443,maximum_requests:1,redirects_allowed:false,production_allowed:false}),email_identity_reference:'owner-primary-email',provider_event_reference:'sha256:'+ 'p'.repeat(64),verified_at:'2026-10-07T19:43:57.000Z',state:'VERIFIED'}]};if(String(sql).includes('INSERT'))creates++;throw new Error('unexpected');},release(){}};}}const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:P,runtime:runtime()});const authorizationInput={operator_id:'human:owner',tenant_id:'grupo_erick',environment:'staging',authorization_scope:'PUBLIC_WEB_CANARY_SINGLE_EXECUTION_NON_PRODUCTION',target_origin:'https://staging.example.org',target_path:'/health',method:'GET',port:443,maximum_requests:1,redirects_allowed:false,production_allowed:false,};const r=await c.resumeEmailReauthDurableComposition({evidence_key:'sha256:'+ 'e'.repeat(64),authorizationInput});assert.equal(r.ok,true);assert.equal(r.status,'PUBLIC_WEB_CANARY_EMAIL_REAUTH_DURABLE_GRANT_READY_NOT_EXECUTED');assert.equal(r.receipt.durable,true);assert.equal(r.execution_authorized,false);assert.equal(r.external_network_called,false);assert.equal(creates,0);assert.equal(JSON.stringify(r).includes('activation_confirmation'),false);await c.close();});

test('rejects caller supplied single-use identities',async()=>{class P extends Pool{connect(){return {query:async()=>({rowCount:1,rows:[{evidence_key:'sha256:'+ 'e'.repeat(64),challenge_id:'sha256:'+ 'c'.repeat(64),subject_id:'human:owner',action_digest:require('../src/core/canonical-content-digest').computeCanonicalContentDigest({environment:'staging',target_origin:'https://staging.example.org',target_path:'/health',method:'GET',port:443,maximum_requests:1,redirects_allowed:false,production_allowed:false}),email_identity_reference:'owner-primary-email',provider_event_reference:'sha256:'+ 'p'.repeat(64),verified_at:'2026-10-07T19:43:57.000Z',state:'VERIFIED'}]}),release(){}};}}const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:P,runtime:runtime()});const r=await c.resumeEmailReauthDurableComposition({evidence_key:'sha256:'+ 'e'.repeat(64),authorizationInput:{replay_key:'caller-controlled'}});assert.equal(r.ok,false);assert.equal(r.reason,'caller_single_use_identity_forbidden');await c.close();});
