'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createChallenge}=require('../scripts/public-web-canary-email-reauth-challenge');
let poolConfig;class Pool{constructor(config){poolConfig=config;this.rows=[]}connect(){return Promise.resolve({query:async()=>({rowCount:1,rows:[{challenge_id:'x'}]}),release(){}})}end(){return Promise.resolve()}}
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reauth-challenge-'));const ca=path.join(dir,'ca.pem');fs.writeFileSync(ca,'-----BEGIN CERTIFICATE-----\ntest-only\n-----END CERTIFICATE-----\n');process.on('exit',()=>fs.rmSync(dir,{recursive:true,force:true}));
const env={POSTGRES_HOST:'aws-0-sa-east-1.pooler.supabase.com',POSTGRES_PORT:'5432',POSTGRES_USER:'postgres.vvzvqinbzdqzcwrfoomd',POSTGRES_PASSWORD:'opaque',POSTGRES_DB:'postgres',HERMES_STAGING_CA_FILE:ca,HERMES_REAUTH_TARGET_ORIGIN:'https://staging.example.org',HERMES_REAUTH_TARGET_PATH:'/health'};
test('creates explicit staging-bound challenge without execution authority',async()=>{const r=await createChallenge({PoolClass:Pool,env,clock:()=> '2026-10-07T03:30:00.000Z'});assert.equal(r.ok,true);assert.match(r.action_digest,/^sha256:[0-9a-f]{64}$/);assert.equal(r.production_allowed,false);assert.equal(r.execution_authorized,false);assert.equal(r.identity_alias,'owner-primary-email');assert.equal(poolConfig.host,env.POSTGRES_HOST);assert.equal(poolConfig.ssl.rejectUnauthorized,true);});
test('fails closed without staging database configuration',async()=>{await assert.rejects(()=>createChallenge({PoolClass:Pool,env:{HERMES_REAUTH_TARGET_ORIGIN:'https://staging.example.org',HERMES_REAUTH_TARGET_PATH:'/health'},clock:()=> '2026-10-07T03:30:00.000Z'}),/postgres_environment_invalid/)});
test('blocks missing or placeholder target before opening postgres',async()=>{for(const target of [undefined,'https://example.com','http://staging.example.org']){const custom={...env,HERMES_REAUTH_TARGET_ORIGIN:target};await assert.rejects(()=>createChallenge({PoolClass:Pool,env:custom}),/explicit_valid_non_placeholder_canary_target_required/);}});
test('challenge digest binds origin and path exactly',async()=>{const a=await createChallenge({PoolClass:Pool,env,clock:()=> '2026-10-07T03:30:00.000Z'});const b=await createChallenge({PoolClass:Pool,env:{...env,HERMES_REAUTH_TARGET_PATH:'/status'},clock:()=> '2026-10-07T03:30:00.000Z'});assert.notEqual(a.action_digest,b.action_digest);});
test('rejects localhost database for operational reauth',async()=>{await assert.rejects(()=>createChallenge({PoolClass:Pool,env:{...env,POSTGRES_HOST:'127.0.0.1'}}),/staging_postgres_identity_invalid/);});
