'use strict';
const assert=require('node:assert/strict'); const test=require('node:test');
const {createPublicWebCanaryOperationalPostgresBootstrap}=require('../src/pilots/public-web-canary-operational-postgres-bootstrap');
class Pool { constructor(config){this.config=config;this.ended=0;} async query(sql){ if(String(sql).includes('information_schema')) return {rows:[{schema_exists:true,table_exists:true,columns_exist:true}]}; throw new Error('unexpected'); } async end(){this.ended++;} connect(){throw new Error('not used');} }
function runtime(){return {operationalBootstrapConfigured:true,stagingRealTransportOptIn:true,environment:'staging',production:false,production_allowed:false,maximum_requests:1,rollout_percentage:1,
 featureFlagResolver:async()=>true,killSwitchResolver:async()=>false,
 ...Object.fromEntries(['canarySessionRegistry','targetAllowlist','adapterRegistry','lifecycleRegistry','configurationRegistry','secretReferenceRegistry','secretResolver','readinessResult','rateLimitBudget','costBudget','operatorPolicy'].map(k=>[k,{}])),clock:()=>new Date()};}
const env={POSTGRES_PORT:'5432',POSTGRES_USER:'u',POSTGRES_PASSWORD:'opaque',POSTGRES_DB:'d'};
test('composes official durable audit without exposing credential material',async()=>{const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:Pool,runtime:runtime()});assert.equal(c.bootstrap.ok,true);assert.equal(c.bootstrap.auditSink.durable,true);assert.equal(c.bootstrap.requireDurableAudit,true);assert.equal(c.credential_material_present,false);assert.equal(JSON.stringify(c).includes('opaque'),false);assert.deepEqual(await c.bootstrap.auditSink.ensureReady(),{ok:true,status:'READY'});await c.close();await c.close();});
test('fails closed before pool creation when postgres environment is incomplete',()=>{let made=0;class P extends Pool{constructor(x){super(x);made++;}}assert.throws(()=>createPublicWebCanaryOperationalPostgresBootstrap({environment:{POSTGRES_PORT:'5432'},PoolClass:P,runtime:runtime()}),/postgres_environment_invalid/);assert.equal(made,0);});
test('production-shaped runtime remains blocked by staging bootstrap',()=>{const r=runtime();r.production_allowed=true;const c=createPublicWebCanaryOperationalPostgresBootstrap({environment:env,PoolClass:Pool,runtime:r});assert.equal(c.bootstrap.ok,false);assert.equal(c.bootstrap.blocked_reason,'production_blocked');});
