'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {prepareStrongHumanReauthEmail,verifyStrongHumanReauthEmail}=require('../src/core/strong-human-reauth-email-contract');
const {authorizePublicWebCanaryWithEmailReauth}=require('../src/core/public-web-canary-email-reauth-authorization');
const now='2026-10-07T03:00:00.000Z';
function verified(){const c=prepareStrongHumanReauthEmail({subject_id:'human:owner',action_digest:'sha256:canary-action',email_identity_reference:'oauth-email:owner',ttl_seconds:300,production_allowed:false},{clock:()=>now});return verifyStrongHumanReauthEmail(c,{provider_authenticated:true,channel:'email',provider_event_id:'provider:evt:1',authenticated_subject_id:'human:owner',email_identity_reference:'oauth-email:owner',challenge_id:c.challenge_id,action_digest:c.action_digest,single_use:true,consumed:false,verified_at:now},{clock:()=>now});}
function input(overrides={}){return {reauth:verified(),operator_id:'human:owner',environment:'staging',authorization_scope:'PUBLIC_WEB_CANARY_SINGLE_EXECUTION_NON_PRODUCTION',target_origin:'https://example.com',target_path:'/',method:'GET',port:443,maximum_requests:1,redirects_allowed:false,production_allowed:false,replay_key:'replay:1',request_reference:'request:1',grant_nonce:'grant:1',reservation_nonce:'reservation:1',...overrides};}
test('creates parallel single-use grant readiness from verified email reauth',()=>{const r=authorizePublicWebCanaryWithEmailReauth(input());assert.equal(r.ok,true);assert.equal(r.approval_mode,'STRONG_HUMAN_REAUTH_EMAIL');assert.equal(r.execution_authorized,false);assert.equal(r.remaining_execution_count,1);});
test('does not weaken dual-control path and fails without provider-verified reauth',()=>{const r=authorizePublicWebCanaryWithEmailReauth(input({reauth:{ok:false}}));assert.equal(r.ok,false);});
test('binds authenticated subject and exact fixed canary target',()=>{assert.equal(authorizePublicWebCanaryWithEmailReauth(input({operator_id:'human:other'})).ok,false);assert.equal(authorizePublicWebCanaryWithEmailReauth(input({target_origin:'https://openai.com'})).ok,false);});
test('blocks production and nonce reuse',()=>{assert.equal(authorizePublicWebCanaryWithEmailReauth(input({production_allowed:true})).ok,false);assert.equal(authorizePublicWebCanaryWithEmailReauth(input({reservation_nonce:'grant:1'})).ok,false);});
