'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {composeEmailReauthOperationalBridge}=require('../src/core/public-web-canary-email-reauth-operational-composer');
const d=x=>'sha256:'+x.repeat(64);
const binding={ok:true,status:'PUBLIC_WEB_CANARY_EMAIL_REAUTH_RUNTIME_BOUND',tenant_id:'grupo_erick',trial_id:'public_web_email_reauth_trial:'+d('1'),plan_hash:d('2'),environment:'staging',target_origin:'https://hermes-staging.grupoerick.tech',target_path:'/health',production_allowed:false};
const grant={ok:true,status:'PUBLIC_WEB_CANARY_EMAIL_REAUTH_BRIDGE_GRANT_READY_NOT_EXECUTED',authorization_grant_id:'grant:1',execution_reservation_id:'reservation:1',grant_reservation_fingerprint:d('3'),authorization_grant:{environment:'staging'},execution_reservation:{tenant_id:binding.tenant_id,trial_id:binding.trial_id,plan_hash:binding.plan_hash,replay_key:'replay:1',reservation_nonce:'nonce:1'}};
test('composes deterministic bridge input without confirmation or execution authority',()=>{const input={grantResult:grant,runtimeBinding:binding,requested_at:'2026-10-07T10:00:00.000Z'};const a=composeEmailReauthOperationalBridge(input),b=composeEmailReauthOperationalBridge(input);assert.deepEqual(a,b);assert.equal(a.ok,true);assert.equal(a.execution_authorized,false);assert.equal(a.external_network_called,false);assert.equal(a.production_allowed,false);assert.equal(Object.hasOwn(a.bridgeInput,'activation_confirmation'),false);assert.equal(a.bridgeInput.execution_count,1);assert.equal(a.bridgeInput.runner_request.target_path,'/health');for(const k of ['write_allowed','action_allowed','send_allowed','publish_allowed','delete_allowed'])assert.equal(a.bridgeInput[k],false);});
test('fails closed on grant/runtime binding mismatch',()=>{const r=composeEmailReauthOperationalBridge({grantResult:{...grant,execution_reservation:{...grant.execution_reservation,plan_hash:d('9')}},runtimeBinding:binding,requested_at:'2026-10-07T10:00:00.000Z'});assert.equal(r.ok,false);assert.equal(r.reason,'grant_runtime_binding_mismatch');});
test('requires canonical timestamp and staging binding',()=>{assert.equal(composeEmailReauthOperationalBridge({grantResult:grant,runtimeBinding:binding,requested_at:'not-time'}).ok,false);assert.equal(composeEmailReauthOperationalBridge({grantResult:grant,runtimeBinding:{...binding,environment:'production'},requested_at:'2026-10-07T10:00:00.000Z'}).ok,false);});
