'use strict';const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {validateInput}=require('../scripts/public-web-canary-email-reauth-evidence');
const input={handoff:{ok:true,status:'EMAIL_REAUTH_PROVIDER_HANDOFF_READY',identity_alias:'owner-primary-email',delivery_reference:'d',challenge_id:'c',action_digest:'a'},delivery:{message_id:'m1',thread_id:'t1',delivery_reference:'d',email_ts:'2026-10-07T17:54:04.000Z'},reply:{id:'m2',thread_id:'t1',from:'owner@example.test',body:'APROVAR REAUTENTICACAO HERMES',email_ts:'2026-10-07T17:54:22.000Z'},profile:{authenticated:true,identity_alias:'owner-primary-email',email:'owner@example.test'}};
test('accepts only closed evidence input schema',()=>{assert.equal(validateInput(input),true);assert.equal(validateInput({...input,command:'sh'}),false);assert.equal(validateInput({...input,reply:{...input.reply,token:'x'}}),false);});
test('wrapper is fixed and does not expose env or accept arguments',()=>{const s=fs.readFileSync(path.join(__dirname,'../scripts/public-web-canary-email-reauth-evidence-operational-wrapper.sh'),'utf8');assert.match(s,/\[ "\$#" -eq 0 \]/);assert.match(s,/exec node/);assert.doesNotMatch(s,/eval|sh -c|bash -c|cat "?\$ENV_FILE/);});
const os=require('node:os');const {persistOperationalEvidence}=require('../scripts/public-web-canary-email-reauth-evidence');
async function simulate(rows){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reauth-test-'));const file=path.join(dir,'proof.json');const ca=path.join(dir,'ca.pem');fs.writeFileSync(file,JSON.stringify(input),{mode:0o600});fs.writeFileSync(ca,'-----BEGIN CERTIFICATE-----\ntest-only\n-----END CERTIFICATE-----\n');const calls=[];let ended=false;class Pool{async connect(){return {query:async(sql)=>{calls.push(sql);if(sql.startsWith('UPDATE'))return {rowCount:rows[0]};if(sql.startsWith('INSERT'))return {rowCount:rows[1]};return {};},release(){calls.push('RELEASE');}};}async end(){ended=true;}}const env={POSTGRES_HOST:'aws-0-sa-east-1.pooler.supabase.com',POSTGRES_PORT:'5432',POSTGRES_USER:'postgres.vvzvqinbzdqzcwrfoomd',POSTGRES_PASSWORD:'test',POSTGRES_DB:'postgres',HERMES_STAGING_CA_FILE:ca};try{const result=await persistOperationalEvidence({PoolClass:Pool,env,inputPath:file}).then(value=>({value}),error=>({error}));return {...result,calls,ended};}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('operational persistence commits atomically',async()=>{const r=await simulate([1,1]);assert.equal(r.value.ok,true);assert.equal(r.value.execution_authorized,false);assert.equal(r.calls.includes('COMMIT'),true);assert.equal(r.ended,true);});
test('operational persistence rejects expired challenge before insert',async()=>{const r=await simulate([0,1]);assert.ok(r.error);assert.equal(r.calls.includes('ROLLBACK'),true);assert.equal(r.calls.some(s=>s.startsWith('INSERT')),false);assert.equal(r.ended,true);});
test('operational persistence rolls back on evidence conflict',async()=>{const r=await simulate([1,0]);assert.ok(r.error);assert.equal(r.calls.includes('ROLLBACK'),true);assert.equal(r.calls.includes('COMMIT'),false);assert.equal(r.ended,true);});
