'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {prepareStrongHumanReauthEmail,verifyStrongHumanReauthEmail}=require('../src/core/strong-human-reauth-email-contract');
const {authorizePublicWebCanaryWithEmailReauth}=require('../src/core/public-web-canary-email-reauth-authorization');
const now='2026-10-07T03:00:00.000Z';
function verified(){return {ok:true,status:'EMAIL_REAUTH_DURABLE_EVIDENCE_CONFIRMED',durable:true,single_use:true,subject_id:'human:owner',challenge_id:'sha256:'+ 'a'.repeat(64),action_digest:'sha256:'+ 'b'.repeat(64),provider_event_reference:'sha256:'+ 'c'.repeat(64),evidence_key:'sha256:'+ 'd'.repeat(64),email_identity_reference:'owner-primary-email',verified_at:now};}
function input(overrides={}){return {reauth:verified(),operator_id:'human:owner',environment:'staging',authorization_scope:'PUBLIC_WEB_CANARY_SINGLE_EXECUTION_NON_PRODUCTION',target_origin:'https://example.com',target_path:'/',method:'GET',port:443,maximum_requests:1,redirects_allowed:false,production_allowed:false,replay_key:'replay:1',request_reference:'request:1',grant_nonce:'grant:1',reservation_nonce:'reservation:1',...overrides};}
test('creates parallel single-use grant readiness from verified email reauth',()=>{const r=authorizePublicWebCanaryWithEmailReauth(input());assert.equal(r.ok,true);assert.equal(r.approval_mode,'STRONG_HUMAN_REAUTH_EMAIL');assert.equal(r.execution_authorized,false);assert.equal(r.remaining_execution_count,1);});
test('does not weaken dual-control path and fails without provider-verified reauth',()=>{const r=authorizePublicWebCanaryWithEmailReauth(input({reauth:{ok:false}}));assert.equal(r.ok,false);});
test('binds authenticated subject and exact fixed canary target',()=>{assert.equal(authorizePublicWebCanaryWithEmailReauth(input({operator_id:'human:other'})).ok,false);assert.equal(authorizePublicWebCanaryWithEmailReauth(input({target_origin:'https://openai.com'})).ok,false);});
test('blocks production and nonce reuse',()=>{assert.equal(authorizePublicWebCanaryWithEmailReauth(input({production_allowed:true})).ok,false);assert.equal(authorizePublicWebCanaryWithEmailReauth(input({reservation_nonce:'grant:1'})).ok,false);});
