'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createStrongHumanReauthEmailPostgres}=require('../src/adapters/postgres/strong-human-reauth-email-postgres');
function pool(results){return{connect:async()=>({query:async(sql)=>{if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return{rowCount:null};return results.shift();},release(){}})}}
test('persists challenge once',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:1}])});const r=await a.createChallenge({ok:true,status:'STRONG_HUMAN_REAUTH_EMAIL_CHALLENGE_PREPARED',challenge_id:'c',subject_id:'s',action_digest:'d',email_identity_reference:'e',issued_at:'2026-10-07T03:00:00.000Z',ttl_seconds:300});assert.equal(r.ok,true);});
test('blocks challenge replay',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:0}])});const r=await a.createChallenge({ok:true,status:'STRONG_HUMAN_REAUTH_EMAIL_CHALLENGE_PREPARED',challenge_id:'c',subject_id:'s',action_digest:'d',email_identity_reference:'e',issued_at:'2026-10-07T03:00:00.000Z',ttl_seconds:300});assert.equal(r.ok,false);});
test('atomically consumes verified evidence once',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:1}])});const r=await a.verifyAndConsume({ok:true,status:'STRONG_HUMAN_REAUTH_EMAIL_VERIFIED_SINGLE_USE_NOT_CONSUMED',challenge_id:'c',provider_event_id:'p',verified_at:'2026-10-07T03:00:01.000Z',subject_id:'s',action_digest:'d',email_identity_reference:'e'});assert.equal(r.ok,true);assert.equal(r.consumed,true);assert.equal(r.execution_authorized,false);});
test('fails closed when CAS cannot consume',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:0}])});const r=await a.verifyAndConsume({ok:true,status:'STRONG_HUMAN_REAUTH_EMAIL_VERIFIED_SINGLE_USE_NOT_CONSUMED',challenge_id:'c',provider_event_id:'p',verified_at:'2026-10-07T03:00:01.000Z',subject_id:'s',action_digest:'d',email_identity_reference:'e'});assert.equal(r.ok,false);assert.equal(r.consumed,false);});

test('expires only a pending challenge through official adapter',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:1}])});const r=await a.expireChallenge('sha256:'+ 'a'.repeat(64));assert.equal(r.ok,true);assert.equal(r.status,'EMAIL_REAUTH_CHALLENGE_EXPIRED');});
test('expiration fails closed when challenge is absent or already consumed',async()=>{const a=createStrongHumanReauthEmailPostgres({pool:pool([{rowCount:0}])});const r=await a.expireChallenge('sha256:'+ 'b'.repeat(64));assert.equal(r.ok,false);});
