'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const {prepareStrongHumanReauthEmail,verifyStrongHumanReauthEmail}=require('../src/core/strong-human-reauth-email-contract');
const now='2026-10-07T03:00:00.000Z';
function challenge(overrides={}){return prepareStrongHumanReauthEmail({subject_id:'human:owner',action_digest:'sha256:canary-action',email_identity_reference:'oauth-email:owner',ttl_seconds:300,production_allowed:false,...overrides},{clock:()=>now});}
test('prepares reference-only challenge without authorizing execution',()=>{const r=challenge();assert.equal(r.ok,true);assert.equal(r.execution_authorized,false);assert.equal(r.delivery_performed,false);assert.equal(r.credential_material_present,false);});
test('rejects raw email and secret material',()=>{assert.equal(challenge({email_address:'owner@example.invalid'}).ok,false);assert.equal(challenge({otp:'123456'}).ok,false);});
test('requires authenticated provider evidence bound to subject identity and action',()=>{const c=challenge();const r=verifyStrongHumanReauthEmail(c,{provider_authenticated:true,channel:'email',provider_event_id:'evt:1',authenticated_subject_id:'human:owner',email_identity_reference:'oauth-email:owner',challenge_id:c.challenge_id,action_digest:c.action_digest,single_use:true,consumed:false,verified_at:now},{clock:()=>now});assert.equal(r.ok,true);assert.equal(r.verified,true);assert.equal(r.execution_authorized,false);});
test('fails closed on forged identity, replay-shaped evidence, or expiry',()=>{const c=challenge();const base={provider_authenticated:true,channel:'email',provider_event_id:'evt:1',authenticated_subject_id:'human:owner',email_identity_reference:'oauth-email:owner',challenge_id:c.challenge_id,action_digest:c.action_digest,single_use:true,consumed:false,verified_at:now};assert.equal(verifyStrongHumanReauthEmail(c,{...base,authenticated_subject_id:'human:other'},{clock:()=>now}).ok,false);assert.equal(verifyStrongHumanReauthEmail(c,{...base,consumed:true},{clock:()=>now}).ok,false);assert.equal(verifyStrongHumanReauthEmail(c,base,{clock:()=> '2026-10-07T03:11:00.000Z'}).ok,false);});
